ocamllabs/vscode-ocaml-platform

package.json
snippets/ocaml.json

@imbsky feel free to push here

Add initial snippet support to OCaml

---

snippets/ocaml.json
syntaxes/ocaml.json

I looked over the OCaml grammar and snippets, improving a few things:
- the lambda snippet includes the `fun` keyword
- unicode escape sequence has between 1 and 6 digits
- an underscore is considered a constant pattern instead of a keyword
- the empty list constructor is highlighted

Tweak OCaml syntax highlighting and snippets

---

CHANGELOG.md
languages/ocamllex.json
syntaxes/menhir.json
syntaxes/ocaml.json
syntaxes/ocamllex.json

This PR fixes some bugs with the ocamllex configuration and grammar. Also, since the OCaml grammar already defines patterns for strings and characters, I made it so the ocamllex and menhir grammars just reference the existing patterns (`source.ocaml#strings` & `source.ocaml#characters`).
- Adds keyword highlighting for `shortest`, `refill`, `as`
- OCaml block comments are used instead of C-style block comments
- Comments are correctly highlighted (dimmed for my theme)
- Curly brackets in string literals don't escape the string and break highlighting
- In the OCaml grammar, character literals are now `constant.character` instead of `string.quoted`
Comparison:
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/78325498-978f8e80-752c-11ea-9090-3deb1bed7a89.png …

Rewrite OCamllex grammar

---

CHANGELOG.md
syntaxes/ocaml.json
syntaxes/ocamllex.json

Fix bugs that arose from interactions between the OCaml and ocamllex/ocamlyacc syntaxes:
| Old | New |
| - | - |
| ![mly_old](https://user-images.githubusercontent.com/25037249/78420419-d17f9400-7603-11ea-9f79-c1a73e971101.png) | ![mly_new](https://user-images.githubusercontent.com/25037249/78420421-d5131b00-7603-11ea-8e6a-a917f49eadef.png) |
| ![mll_old](https://user-images.githubusercontent.com/25037249/78420413-c4fb3b80-7603-11ea-9784-54c5bc83bfe7.png) | ![mll_new](https://user-images.githubusercontent.com/25037249/78420415-ca588600-7603-11ea-8889-0fa3504ce70e.png) | 
Add highlighting for aggregate literals and `.`/`,`/`;` symbols in OCaml sources:
| Old | New |
| - | - |
| ![ml_old](https://user-images.githubusercontent.com/25037249/78420434-068be680-7604-11ea-8b5e-1eb116d90008.png) | …

Improve ocaml and ocamllex/ocamlyacc syntax

---

syntaxes/ocaml.json

- Printf placeholders (those that begin with `%`) are no longer highlighted in `external` declarations
- Invalid printf placeholders are no longer highlighted because `%` can appear in other contexts where it is not an error
- OCaml sources are highlighted inside ocamldoc comments
- ocamldoc comments no longer have the `emphasis` tag because ocamldoc comments can have text formatting for italics
Comparison:
| Old | New |
| - | - |
| ![printf_old](https://user-images.githubusercontent.com/25037249/78469076-6a7ce080-76d2-11ea-85f3-aeaa1af4f5e8.png) | ![printf_new](https://user-images.githubusercontent.com/25037249/78469077-6cdf3a80-76d2-11ea-8895-c54b105e6329.png) | 
| ![doc_old](https://user-images.githubusercontent.com/25037249/78469081-82546480-76d2-11ea-802e-7f6a8a12014c.png) | …

Improve OCaml syntax highlighting in strings and doc comments

---

CHANGELOG.md
languages/ocamlformat.json
package.json
syntaxes/ocamlformat.json

Add OCamlFormat syntax highlighting

---

README.md

At first glance, I thought those two were different things while actually they redirect to the same project.
I guess that using the same name for both might avoid some confusion.

readme: avoid confusion between ocaml-lsp and ocaml-lsp-server

---

.gitignore
src/Cmd.ml
src/Cmd.mli
src/Extension.ml
src/Promise.ml
src/Setup.ml
src/Toolchain.ml
src/Toolchain.mli
src/__tests__/Bindings_tests.ml
src/bindings/Node.ml
src/bindings/Vscode.ml
src/bindings/Vscode.mli
src/esy.ml
src/esy.mli
src/opam.ml
src/opam.mli
src/path.ml
src/path.mli
src/settings.ml

This removes all the reliance on a "projectRoot". This does not make
sense for workspaces with multiple directories.
For now, this creates an awkward situation for esy projects as it means
that only a single LSP server is used for all projects in the workspace.

Fix support for multi dir workspaces

---

syntaxes/ocamlformat.json

Some options weren't being highlighted correctly before.
| Old | New |
| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/79367611-0264a080-7f03-11ea-9f5c-3ff79f613e7e.png) | ![new](https://user-images.githubusercontent.com/25037249/79367622-05f82780-7f03-11ea-8040-56703c110d2e.png) |

Fix ocamlformat option highlighting

---

src/Toolchain.ml

Following up on conversation in Slack. Existing command check was blocking initialization of extension. 
Instead of using external command I decided to just use `--help` argument as it will be hard to check something like `/usr/local/bin/opam exec --switch=[switch-path] -- ocamllsp` otherwise.

Fix LSP command check

---

src/Extension.ml

We discussed merging error and suggestion messages but I think that error still useful sometimes.  Here's my proposal:
— At the start, check if there is active configuration
— If there is, try to run `ocamllsp` with it, if it fails, show the error
— If there is not, show the suggestion and fall back to Global
— If there is global `ocamllsp`, run it
— If there is no global `ocamllsp`, do nothing, wait until configured.
— After user configures extension, we are back at square one.
Here are all of the possible cases:
**User has no active configuration, has no global `ocamllsp`**
User gets "Select toolchain" message.
**User has no active configuration, has global `ocamllsp`**
User gets "Select toolchain" message.
Extension starts working using global `ocamllsp` 
**User has active …

Do not show error on fallback

---

CHANGELOG.md
package.json
syntaxes/dune-project.json
syntaxes/dune-workspace.json
syntaxes/dune.json

Adds syntax highlighting for dune-workspace files:
I will rewrite the syntax highlighting for `dune` files after this.

dune-workspace syntax highlighting

---

syntaxes/ocaml.json

Fixes a few bugs with the existing OCaml syntax highlighting: 
- External declaration assigned to multiple strings should not highlight printf or escape characters
- Literals should not be highlighted inside of identifiers
- Escaped newlines should be highlighted
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/80849122-a3717d80-8bca-11ea-8112-44c27b9bbd68.png) | ![new](https://user-images.githubusercontent.com/25037249/80849126-a79d9b00-8bca-11ea-9f77-67928aa96be8.png) |

Tweak OCaml syntax highlighting

---

syntaxes/dune-project.json

Highlights the slash for `github` sources inside `dune-project` files as a keyword instead of an operator.
Pictured is the old version. With this change, the slash will be the same color as the `github`.

keyword highlighting for github slash

---

syntaxes/ocaml.json

Currently if users have an extension that highlights parentheses like [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2), parentheses are incorrectly highlighted inside character literals.
This adds the `string.quoted.other.ocaml` tag to character literals so symbols are not highlighted inside them.
| Old | New |
| - | - |
|![old](https://user-images.githubusercontent.com/25037249/80895645-e9e2dd00-8c9b-11ea-8f81-7ef41feb4c82.png)|![new](https://user-images.githubusercontent.com/25037249/80895648-ec453700-8c9b-11ea-9bac-8675f50ed50b.png)|

fix ocaml character highlighting

---

syntaxes/ocaml.json

- Attributes should be highlighted in external declarations
- Bindings are only highlighted when a single variable is introduced
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/81039843-e481c000-8e5e-11ea-8311-8448ec63530c.png) | ![new](https://user-images.githubusercontent.com/25037249/81039846-e6e41a00-8e5e-11ea-942d-dbbc92b08b12.png) |
In the future, the grammar may be modified to highlight bindings inside any pattern.

Tweak OCaml Syntax Highlighting - external declaration and bindings

---

syntaxes/ocaml.json

Closes #180 
OCaml Syntax Highlighting for Quoted Extensions: 
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/81211608-79340d00-8f88-11ea-85ca-8b09eeb4091f.png) | ![new](https://user-images.githubusercontent.com/25037249/81211614-7b966700-8f88-11ea-999b-a5fc3ac8b11a.png) | 
Also fixes a fatal flaw in #175 that prevented function declarations from being highlighted:
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/81213036-a2ee3380-8f8a-11ea-9cd2-16c7257aebb7.png) | ![new](https://user-images.githubusercontent.com/25037249/81213046-a681ba80-8f8a-11ea-9b8a-99a801a0cc0c.png) |

Improve OCaml Syntax Highlighting

---

src/Promise.ml
src/esy.ml
src/path.ml
src/path.mli

Right now we only looking for esy in projectRoot, but sometimes esy can be configured in some other parent folder.
This is a dirty implementation of looking in parent directories. Is there a better way to do it? cc @rgrinberg @prometheansacrifice

Discover esy in parent folders

---

.github/workflows/print_esy_cache.js
.github/workflows/workflow.yml
.prettierrc.json

This PR adds caching for all esy, yarn and opam.
- yarn caching is taken from GH actions [example](https://github.com/actions/cache/blob/master/examples.md#node---yarn).
- esy from hello-reason [workflow](https://github.com/esy-ocaml/hello-reason/tree/master/.github/workflows).
- opam is more rough, it just takes the whole opam root folder calling `opam config var root` and stores it.
There are still ~5min that are spent calling the "use OCaml" action, as I guess it creates the switch etc. This is unnecessary as the cache has everything already, but I don't know if there's a cross-platform way to just install opam. If there is, we could use it when the workflow detects a cache hit.
Before ([example](https://github.com/ocamllabs/vscode-ocaml-platform/actions/runs/100010339)): 32m 0s 
After …

[CI] Cache esy, opam and yarn folders

---

src/DuneFormatter.ml

The dune formatting should only pass the document contents through stdin. A bug that was left in passed the document fileName, which formatted the outdated version of the file.

Fix Dune Formatting 

---

package.json

It was already unused before and listed as deleted in earlier versions.

Remove ocaml.lsp.path as a listed configuration

---

CHANGELOG.md
package.json

Since ocaml 4.09, when an error covers multiple lines, the message
emitted by the compiler looks like this:
```
File "robustmatch.ml", lines 33-37, characters 6-23:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
(AB, MAB, A)
```
This commit detects the presence of an eventual end line. Support of
previous version of the compiler or single line errors is preserved.

Add support of 4.09+ multi lines errors in problem matcher

---

syntaxes/ocaml.interface.json

I can't find any documentation of the`struct` keyword being used in .mli files, so it was probably a typo.

Don't highlight struct keyword in mli files

---

src/Extension.ml
src/Output.ml
src/Output.mli
src/bindings/Vscode.ml
src/bindings/Vscode.mli
src/import.ml

Closes #231 
The `log` function now outputs to the *OCaml Extension* output channel.
All `LanguageClient` instances now share a single *OCaml Language Server* output channel, to avoid adding duplicate channels. Before, there were many duplicate channels with 1 or 2 log statements, but only one output channel was being used for all of the log statements.
| Before |
| - |
| ![many channels](https://user-images.githubusercontent.com/25037249/85375412-1cb29000-b4eb-11ea-892b-bafe93f6836c.png) |
These changes should make it easier for users and developers to understand what the extension and language server are doing.

Unify output channels for logging

---

syntaxes/ocaml.json

Previously, an empty comment `(**)` would be handled as an unclosed ocamldoc comment which is incorrect.
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/86500381-6732d880-bd45-11ea-8136-125895bac1cb.png) | ![new](https://user-images.githubusercontent.com/25037249/86500385-6bf78c80-bd45-11ea-9d39-d4f16987b495.png) |

Fix highlighting of empty comments

---

src/Extension.ml

> By the way, I just realized that we need to register `mly`, `mll` files with the server for this to work on the server side. We should probably do that first in a separate PR.
_Originally posted by @rgrinberg in https://github.com/ocamllabs/vscode-ocaml-platform/pull/270#issuecomment-653849011_

Register ocamllex and menhir with language server

---

CHANGELOG.md
syntaxes/ocaml.json

https://caml.inria.fr/pub/docs/manual-ocaml/attributes.html#floating-attribute
Previously, only normal attributes and item attributes were highlighted due to a typo.

Highlight floating attributes

---

test/suite/esy.test.js

The `There should only be one diagnostic in the Reason source file` test seem to fail in the CI randomly. 
I don't believe we've received any issues from Reason users about problems with diagnostics so we should remove the test for now.

Remove inconsistent Esy tests

---

CHANGELOG.md
package.json

Sometimes opam files do not have a prefix like `packagename.opam` and are just `opam` (like in the opam-repository packages). 
Previously, only opam files with prefixes were highlighted. This PR adds detection for the unprefixed files.

Highlight unprefixed opam files

---

CHANGELOG.md
syntaxes/ocaml.interface.json

http://caml.inria.fr/pub/docs/manual-ocaml/moduletypeof.html
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/87217818-53b5dd80-c302-11ea-92ce-3b46e779d7cd.png) | ![new](https://user-images.githubusercontent.com/25037249/87217820-5b758200-c302-11ea-8dee-cb0e94259670.png) |

Fix syntax highlighting of module type of

---

CHANGELOG.md
syntaxes/ocaml.interface.json

https://ocaml.org/releases/4.10/htmlman/modtypes.html#mod-constraint
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/87477688-628be100-c5dd-11ea-99f2-6af827bd0cdf.png) | ![new](https://user-images.githubusercontent.com/25037249/87477695-661f6800-c5dd-11ea-93f4-4333845f9eec.png) |

Fix syntax highlighting of module constraints

---

CHANGELOG.md
syntaxes/ocamlformat.json

Add syntax highlighting for new ocamlformat values: 
- `after-when-possible`
-  `before-except-val`
- `unset`
https://github.com/ocaml-ppx/ocamlformat/commit/6fb5a8c607b7fb93812870e059dcabe562f88bf5#diff-8f3203cb16efbd72472f28cf96bab086
https://github.com/ocaml-ppx/ocamlformat/commit/403e0206705c47b1f5b123871ca51028d43d878c#diff-8f3203cb16efbd72472f28cf96bab086

Add syntax highlighting for new ocamlformat values

---

CHANGELOG.md
syntaxes/reason.json

Actually it was synchronized with RLS [reason.json](https://github.com/jaredly/reason-language-server/blob/master/editor-extensions/vscode/reason.json)

add support to binding operators on reason

---

CHANGELOG.md
syntaxes/reason.json

It was missing the `:` that exists on Reason when doing type extensions
Buggy example(as you can see on github):
```reason
let x = [%sigi: type t];
let x = 1;
```

fix reason syntax highlighting of type extensions

---

CHANGELOG.md
syntaxes/menhir.json
syntaxes/ocaml.json

OCaml comments can have strings inside of them. Previously the syntax highlighting did not handle this case and would end a comment earlier than the OCaml lexer.
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/87732038-c569ad80-c780-11ea-9175-09f27079331b.png) | ![new](https://user-images.githubusercontent.com/25037249/87732029-bc78dc00-c780-11ea-8857-76f7e1231688.png) |

Improve syntax highlighting of OCaml comments that contain strings

---

CHANGELOG.md
syntaxes/reason.json

Currently there is a problem with recursive modules as you can see here, there is no way that rec can close anything actually, so it's probably a global problem, but made the local fix
```reason
module A: {
module B: {}
};
module rec X: {
module Y: {}
};

fix reason syntax highlighting of rec modules

---

syntaxes/reason.json

The previous PR fixed the content of the first module, this one fixes the next module starting with `and`, as you can see the and isn't highlighted, in the first case
```reason
module rec X: {} = {}
and Y: {} = {};
let rec abc = 1
and def = 1
```

fix reason syntax highlighting of and module

---

syntaxes/META.json
syntaxes/atd.json
syntaxes/cram.json
syntaxes/dune-project.json
syntaxes/dune-workspace.json
syntaxes/dune.json
syntaxes/menhir.json
syntaxes/oasis.json
syntaxes/ocaml.interface.json
syntaxes/ocaml.json
syntaxes/ocamlbuild.json
syntaxes/ocamldoc.json
syntaxes/ocamlformat.json
syntaxes/ocamllex.json
syntaxes/opam-install.json
syntaxes/opam.json

Inspired by the Reason grammar file, I have updated the other language syntaxes to use [Oniguruma character classes](https://github.com/kkos/oniguruma/blob/c5f0ad013490fb6db2a5cb5680028ebcb22fc486/doc/RE#L205) in regex when possible.
Makes it a little easier to read the syntax files.

Use Oniguruma character classes in syntaxes

---

languages/ocaml.json

VSCode already handles indentation for the configured `brackets`, so the regex that handled parentheses in `indentationRules` was unnecessary.
The identation rules for parentheses were also causing problems for some users.

Remove indentationRules for parentheses

---

src/Toolchain.ml

This doesn't change anything except making the log a little more compact

Lsp health check: Use --version instead of --help

---

package.json

Makes the command titles Title-Case to follow the conventions of extension commands.
Also changes the title for "Open a Terminal" to "Create Terminal" to match the VSCode command. I'm not sure if it's necessary to change the command IDs too.

Reword Command Titles

---

CHANGELOG.md
syntaxes/reason.json

Module extensions should be treated the same as pexp_extension
```reason
let x = [%y "abc"];
module X = [%y "abc"];
```

fix reason highlighting of module extension

---

CHANGELOG.md
syntaxes/ocaml.interface.json

The `method` keyword is valid in class types/specifications, which appear in .mli files and module signatures.

Highlight method keyword in ocaml interface

---

CHANGELOG.md
syntaxes/ocaml.interface.json
syntaxes/ocaml.json

Highlighting of `~`:
| Old | New |
| - | - |
| ![label-old](https://user-images.githubusercontent.com/25037249/91643894-08f44000-e9ec-11ea-8b45-6d3b9f5764fb.png) | ![label-new](https://user-images.githubusercontent.com/25037249/91643897-0db8f400-e9ec-11ea-9270-78c92151be2a.png) |
Brackets inside of attributes/extension nodes interacted poorly; see the highlighting of the last `"vscode"`:
| Old | New |
| - | - |
| ![bracket-old](https://user-images.githubusercontent.com/25037249/91643887-f8dc6080-e9eb-11ea-8f73-f0237d34274a.png) | ![bracket-new](https://user-images.githubusercontent.com/25037249/91643928-48bb2780-e9ec-11ea-8687-21d7287f989f.png) |

Improve highlighting of labels and attributes/extensions

---

CHANGELOG.md
syntaxes/ocaml.json

| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/91929814-1b90a280-ec94-11ea-9137-5bfdc9df1b1d.png) | ![after](https://user-images.githubusercontent.com/25037249/91929819-1df2fc80-ec94-11ea-970b-87372184c635.png) |

Fix interaction between character literals and comments/escaped quotes in OCaml files

---

CHANGELOG.md
syntaxes/ocamlformat.json

Closes #324
The equals operator is now `punctuation.separator.key-value`, which is the same value as equal signs in `.gitconfig` or `.conf` files. Whether or not this makes the equals sign a different color from the options depends on the user's theme.
The option values are now highlighting as strings, which makes them a different color from keywords in the Dark+ theme or numbers in the file.
---
VSCode Dark+
| - | - |
| ![before-dark](https://user-images.githubusercontent.com/25037249/91934974-7977b700-eca1-11ea-928a-9983a6156a18.png) | ![after-dark](https://user-images.githubusercontent.com/25037249/91934982-7e3c6b00-eca1-11ea-95d1-80b4cc1f1a81.png) |
Monokai
| - | - |
| ![before-monokai](https://user-images.githubusercontent.com/25037249/91935033-9d …

Make .ocamlformat syntax highlighting more distinct

---

README.md
src/bindings/Vscode.ml
src/bindings/Vscode.mli
src/opam.mli
src/settings.ml

Closes #357
Currently when extension activates and `ocaml.sandbox` is unset, the editor shows 2 error messages:
`Settings.get` was supposed to handle null and undefined gracefully, but bucklescript doesn't seem to consider `null` as `None`.
This PR changes `WorkspaceConfiguration.get` to return `Js.Nullable.t`, which can be safely converted into an `option` in order to handle nulls correctly. The extra error message no longer appears.

Fix error when ocaml.sandbox is unset

---

CHANGELOG.md
syntaxes/ocaml.json

Closes #362 
[quoted-string-id](https://caml.inria.fr/pub/docs/manual-ocaml/lex.html#quoted-string-id) can only contain lowercase letters or underscores in a comment.

Fix highlighting of comments that contain quoted string literals

---

CHANGELOG.md
syntaxes/ocaml.json

The last function's highlighting was fixed:
| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/92632864-0533a980-f287-11ea-8445-4acd630cd764.png) | ![after](https://user-images.githubusercontent.com/25037249/92632914-082e9a00-f287-11ea-8b54-512425f0b3ad.png) |

Fix highlighting of rec keyword in type-annotated functions

---

Makefile
src/Extension.ml
src/TerminalSandbox.ml
src/Toolchain.ml
src/Toolchain.mli
src/opam.ml
src/opam.mli

Shortens the sandbox info displayed in the status bar (at the bottom of the editor) and the created terminal. This is a "prettify" PR but I'm very excited about it! :-)
It now looks like this:
For global sandbox:
For named opam switch (located in ~/.opam):
For local opam switch:
For esy sandbox:
For custom:
-------------
For the `Create Terminal` command:
Global:
Sandbox:

Prettifies sandbox info in status bar and created terminal

---

package.json

On `alt+d`, user gets what they would otherwise get by `cmd+.` to open quick fix options and picking the only option that we have "destruct". 
User still can open quick fix options and pick "destruct" from there or just click on `alt+d`.

add keyboard shortcut for destruct code action

---

.vscode/launch.json
.vscode/tasks.json

They previously had references to BuckleScript files or build system.

Fix launch.json and tasks.json for js_of_ocaml

---

.vscodeignore

Previously semver was incorrectly ignored for packaging the vsix.

Fix vscodeignore for semver node_module

---

CHANGELOG.md
src/bindings/node/node.ml
src/bindings/node/node.mli
src/bindings/node/node_stub.js
src/cmd.ml
src/import.ml
src/path.ml
src/path.mli

Under the Js_of_ocaml build of the extension, `Sys.unix` is always true, which prevents the `Filename` module and `candidates` function from handling Windows paths properly. 
This PR switches to using the Node `path` module for filename functions, and `Platform.t` for the candidates function.

Fix path handling on Windows

---

src/bindings/node/node.ml
src/bindings/node/node.mli
src/esy.ml
src/vscode_ocaml_platform.ml
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

- Keeps the original naming conventions for Node functions.
- Adds some type annotation to the VSCode bindings to make it easier to understand.

Clean up bindings

---

src/dune_task_provider.ml
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

TaskProvider cancellation tokens are no longer optional in VSCode 1.50:
https://github.com/microsoft/vscode/blob/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/src/vs/vscode.d.ts#L6301
https://github.com/microsoft/vscode/blob/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/src/vs/vscode.d.ts#L6316

Update VSCode bindings for 1.50

---

vscode/vscode/vscode.ml

`workspaceFolders` is empty if no folder in vscode is open.
`maybe_list` turns `undefined` results into an empty list.

Handle empty workspaceFolders list

---

README.md

It took me a few seconds of thinking to realize I was supposed to install `ocaml-lsp-server` and not `lsp`.  This is a minor thing for experienced users but I could see it tripping newer users up for awhile with false starts.

Update README instructions to use ocaml-lsp-server from the opam repository

---

src/bindings/node/node.ml

`fs.readFile` can sometimes return a Buffer if the encoding is not provided: https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback
From my quick testing, it seems that it only returns a Buffer if there are less than 24 characters in a file, which is why we didn't catch this issue before.

Fix fs.readFile binding

---

CHANGELOG.md
src/esy.ml
src/toolchain.ml

| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/96499407-39917280-1202-11eb-8ba1-7dccd0b81c92.png) | ![after](https://user-images.githubusercontent.com/25037249/96499415-3c8c6300-1202-11eb-9fde-27af43403b21.png) |
This won't show an option for invalid toolchains though:
https://github.com/ocamllabs/vscode-ocaml-platform/blob/a1e21d0f95304cdf3e3606c296d029eba01aeb7f/src/esy.ml#L34
Should the extension even show an option to select if the package.json is invalid?

Remove duplicate esy sandboxes from package manager selection

---

README.md

I just tried to follow these instructions and it failed trying to build Dune. `ocaml-lsp` no longer builds on old versions of Dune, and new versions of Dune don't build on OCaml 4.06.
It turns out Dune supports building on old compilers via `ocamlfind-secondary` and then everything works.

Add `ocamlfind-secondary` dependency to the `esy` install instructions for BuckleScript

---

CHANGELOG.md
src/vscode_ocaml_platform.ml

Suggested by @ulugbekna
Previously `ocaml.server.restart` would needlessly dispose and recreate the status bar item, dune formatter, and dune task provider when all it needs to do is restart the language server.

Only restart language server for ocaml.server.restart

---

CHANGELOG.md
syntaxes/ocaml.json

`string.quoted.single` (without `character.constant`) is the syntax name used in other programming languages; e.g.,
- https://github.com/microsoft/vscode/blob/master/extensions/cpp/syntaxes/c.tmLanguage.json
- https://github.com/microsoft/vscode/blob/master/extensions/cpp/syntaxes/cpp.tmLanguage.json
- https://github.com/microsoft/vscode/blob/master/extensions/fsharp/syntaxes/fsharp.tmLanguage.json
- https://github.com/microsoft/vscode/blob/master/extensions/rust/syntaxes/rust.tmLanguage.json

Use syntax name for character which is consistent with other programming languages

---

CHANGELOG.md
src/settings.ml
src/settings.mli
src/toolchain.ml
vscode/interop/dune
vscode/interop/interop.ml
vscode/interop/interop.mli

Closes #374
Allows using `${workspaceFolder}` for the sandbox setting's manifest/switch/template. Since this only replaces the variable, it's done during the JSON serialization/deserialization. Relative paths are still not supported, so no command execution logic was changed.
In a workspace editor, it resolves `${workspaceFolder}` with the path of the first workspace folder. If no workspace folders are open, `${workspaceFolder}` is resolved with the value of `Process.cwd`.
When selecting a sandbox, if the path of the workspace folder appears in a discovered configuration, it will be substituted with `${workspaceFolder}`. This makes the sandbox configurations portable by default.

Allow using workspaceFolder placeholder variable for more portable sandbox configurations

---

CHANGELOG.md
package.json
test/runProblemMatcherTests.js
test/suite/problems.js
test/suite/problems.test.js

fix #425 
The error message about an implementation file not matching its signature
does not contain characters. The characters group of the problem match
must hence be optional.
```
File "virtuality2d/src/consts.ml", line 1:
Error: The implementation virtuality2d/src/consts.pp.ml
does not match the interface virtuality2d/src/.virtuality2d.objs/byte/virtuality2d__Consts.cmi:
Values do not match: val g : float is not included in val g : string
File "virtuality2d/src/consts.mli", line 1, characters 0-14:
Expected declaration
File "virtuality2d/src/consts.ml", line 1, characters 4-5:
Actual declaration
```
Note that I have only tested the regex in https://regex101.com/r/13ldQG/1

Support error messages without characters in problem matcher

---

CHANGELOG.md
syntaxes/ocaml.interface.json

Recursive modules types use the rec keyword in mli files: https://ocaml.org/releases/4.11/htmlman/manual024.html#s%3Arecursive-modules

Highlight rec keyword in OCaml mli files for recursive modules

---

src/cmd.ml
src/cmd.mli
src/dune_formatter.ml
src/dune_formatter.mli
src/dune_task_provider.ml
src/dune_task_provider.mli
src/esy.ml
src/esy.mli
src/extension_commands.ml
src/extension_commands.mli
src/extension_consts.ml
src/extension_instance.ml
src/extension_instance.mli
src/import.ml
src/ocaml_lsp.ml
src/opam.ml
src/opam.mli
src/settings.ml
src/terminal_sandbox.mli
src/toolchain.ml
src/toolchain.mli
src/vscode_ocaml_platform.ml
src/vscode_ocaml_platform.mli
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

This is a slightly large change to how to store and manage extension state (was called `Instance` and is called`Extension_instance` now). It removes some mutable state, avoids restarting the instance when we can just update it, and does several other small things. 
For reviewing: I would recommend to go commit by commit from oldest to youngest, and the code should make sense.

Redesign extension state (Instance)

---

src/extension_commands.ml
src/extension_instance.ml
src/terminal_sandbox.ml
src/toolchain.ml
src/toolchain.mli
src/vscode_ocaml_platform.ml

This PR removes the `Package_manager` module and directly integrates its components in the `Toolchain` module.
The separate types (`Toolchain.t` and `Package_manager.t`) have only caused unnecessary conversions between each other, without providing additional functionality.
This PR also cleans up the use of language internally to refer to "toolchains", not "package managers" or "sandboxes". The previous language didn't make sense because only the `Opam`/`Esy` variants could be considered "package managers" and the `Custom`/`Global` variants aren't necessarily sandboxed. 
I didn't change any exposed names, so the commands and settings are still the same (`ocaml.select-sandbox` and `ocaml.sandbox`).

Unify toolchain and package manager types

---

CHANGELOG.md
syntaxes/reason.json

Closes #380
This PR updates parts of the reason syntax to [reason-language-server's version](https://github.com/jaredly/reason-language-server/blob/master/editor-extensions/vscode/reason.json) to fix highlighting bugs.

Fix reason highlighting of let extensions

---

syntaxes/menhir.json

@ALANVF pointed out some lingering issues with the syntax highlighting of Menhir's new syntax:
| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/100265621-6291db00-2f05-11eb-8f74-9066dc25a5f7.png) | ![after](https://user-images.githubusercontent.com/25037249/100265625-658ccb80-2f05-11eb-84e0-01f0784b2035.png) |

Fix Menhir production highlighting in new syntax

---

CHANGELOG.md
package.json
syntaxes/menhir-action.json
syntaxes/menhir.json
syntaxes/ocaml.json

Menhir's syntax highlighting was bad so I decided to fix it.
Possible future improvements:
1) Fix highlighting for attributes (not possible without `#2` below).
2) Generate grammars using OCaml because JSON is terrible.
A lengthy example:
Another example (new merlin syntax):

Drastically improve Menhir syntax highlighting

---

CHANGELOG.md
package.json

Adds an `Alt+P` keybinding to fill a file with an inferred interface.
The workflow is quite smooth from my testing:
- `Alt+O` to switch to  new .mli file.
- `CTRL+S`/ `CMD+S` to save the .mli file.
- `Alt+P` to fill the .mli file with an inferred interface.

Add keyboard shortcut for infer interface code action

---

src/extension_instance.ml
src/ocaml_lsp.ml
src/ocaml_lsp.mli
src/switch_impl_intf.ml

This PR changes the behavior of the switch implementation-interface feature to initialize the interface with an inferred one when switching to a non-existing file.
It depends on https://github.com/ocaml/ocaml-lsp/pull/308.
I implemented a custom request `ocamllsp/inferIntf` in `ocaml-lsp`, because running a codeAction automatically did not seem like a good way to implement this. The code action is still in place though: when switching to an existing interface, we can select some text and replace it with the inferred interface.

Infer interface when switching to an non-existing interface

---

CHANGELOG.md
syntaxes/ocaml.interface.json
syntaxes/ocaml.json

Weak type parameters (`'_weak1`) don't appear in source code, but they do appear in hover type information, so they should be highlighted:
`module type of`:
| - | - |
| ![image](https://user-images.githubusercontent.com/25037249/100773282-834eaa80-33b5-11eb-9618-89d59414d75d.png) | ![image](https://user-images.githubusercontent.com/25037249/100773314-8cd81280-33b5-11eb-9342-d06c544a088d.png) |

Improve syntax highlighting of type parameters and module type of

---

src/opam.ml

The output of the `opam switch show` command contains whitespace, so we need to strip the output.

Fix opam switch detection

---

CHANGELOG.md
syntaxes/ocaml.json

Character literals with an escaped character inside of them should have the same token name as normal character literals (`string.quoted.single.ocaml`). Otherwise, the surrounding single quotes may be a different color from normal character literals.

Fix highlighting of escaped character literals

---

CHANGELOG.md
syntaxes/ocaml.json

Closes #468 
| - | - |
| <img width="190" alt="image" src="https://user-images.githubusercontent.com/25037249/100966619-39afae00-34e2-11eb-85bf-ac7d2dc37380.png"> | <img width="190" alt="image" src="https://user-images.githubusercontent.com/25037249/100966702-6663c580-34e2-11eb-9f6e-35351edc2e40.png"> |

Fix highlighting of comments that contain strings with escaped quotes

---

CHANGELOG.md
src/extension_commands.ml
src/extension_instance.ml
src/extension_instance.mli
src/vscode_ocaml_platform.ml
src/vscode_ocaml_platform.mli

We should initialize the extension and register all commands even if the
language server fails to load.

Initialize extension correctly

---

CHANGELOG.md
syntaxes/menhir.json

Why did it not even occur to me that these existed...

Support token aliases in associativity declarations

---

CHANGELOG.md
README.md
package.json
src/opam.ml

This PR makes the extension execute `ocaml-env exec -- opam` for any opam commands on Windows. Previously, VSCode would have to be opened from cygwin to have a proper opam environment. Now, VSCode can be opened normally and the extension handles the environment.
I made the `ocaml.useOcamlEnv` setting default to true because this should be the smoothest way to use the extension on Windows now. Having the option lets users continue to use the old workflow by accessing `opam` directly.
@tmattio: I think this should (partially) help implement #463 on Windows.

Use ocaml-env for opam commands on windows

---

CHANGELOG.md
package.json
src/extension_instance.ml
src/terminal_sandbox.ml
src/terminal_sandbox.mli

Fixes issue mentioned in https://github.com/ocaml/ocaml-lsp/issues/346#issuecomment-743359650
Once the extension sandbox is set up, creating a terminal should never fail. The previous behavior would not create a terminal if `ocaml.terminal.shell.*` was unset.

Fix terminal creation when using default shell and arguments

---

package.json
src/extension_commands.ml
src/extension_commands.mli
src/opam.ml
src/treeview_commands.ml
src/treeview_commands.mli
src/treeview_help.ml
src/treeview_help.mli
src/treeview_switches.ml
src/treeview_switches.mli
src/vscode_ocaml_platform.ml

This PR improves the registration of tree view providers:
- The registrations are now async and don't depend on each other
- The tree view modules register their own command, so the `Extension_commands` can stay isolated.
cc @ulugbekna

Register provider and commands in treeview modules

---

CHANGELOG.md
src/switch_impl_intf.ml
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

* Fixes https://github.com/ocaml/ocaml-lsp/issues/358 
The PR provides a _quick_ fix. If the new mli file isn't empty, we don't insert inferred interface. 
Not sure whether it is better to replace the contents with the (potentially new) interface or maybe show a diff window with new interface. 
* Adds more structured support for URI schemes
* Improves 'Switch_impl_intf.show_file' by refactoring, renaming, and removing redundant value returned 
---
Reviewing commit by commit should be easiest.

Fix switch impl intf twice

---

README.md
src/sandbox.ml
src/sandbox.mli

ReScript now has its own extension, so we can safely say we don't support it and redirect to the new extension instead.

Remove BuckleScript support instructions

---

assets/arrow-circle-up-dark.svg
assets/arrow-circle-up-light.svg
assets/plus-dark.svg
assets/plus-light.svg
package.json
src/bindings/node/dune
src/bindings/node/node.ml
src/bindings/node/node.mli
src/esy.ml
src/esy.mli
src/extension_commands.ml
src/extension_commands.mli
src/extension_consts.ml
src/extension_instance.ml
src/opam.ml
src/opam.mli
src/path.ml
src/path.mli
src/sandbox.ml
src/sandbox.mli
src/treeview_commands.ml
src/treeview_help.ml
src/treeview_sandbox.ml
src/treeview_sandbox.mli
src/treeview_switches.ml
src/vscode_ocaml_platform.ml
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

This PR adds a sandbox view to the OCaml activity tab.
It builds on top of https://github.com/ocamllabs/vscode-ocaml-platform/pull/497 to provide a cleaner implementation of the treeview using the functorized VSCode bindings.
Where the Opam Switch view displays a list of switches on the user system and the opam packages in each of them, the Sandbox view displays the list of packages installed in the currently selected sandbox.
In addition to the Sandbox view, the following changes have been implemented on the Opam Switch view:
- The direct descendants of the switch are now the "root" packages: the packages that have been installed by the user manually.
- The packages now list their own dependencies
The sandbox view displays the package the same way as the Opam Switch one, that is, the …

Add a sandbox tree view

---

.github/workflows/main.yml

It deploys the pre-built compiler cache for Actions runners in Ubuntu and macOS. It also tries to speed up builds as much as possible by handling the dune and opam caches internally, and it finds the latest OCaml patch version, so maintenance costs are really kept to a minimum. In addition, the log output has been greatly improved.

Use actions-ml instead for CI

---

CHANGELOG.md
README.md
package.json
src/extension_commands.ml
src/extension_commands.mli
src/extension_consts.ml
src/import.ml
src/switch_impl_intf.ml

The PR adds a command to open the dune file located in the same folder the currently open file. The command is available in the command palette iff an ocaml-related (ocaml, reason, etc.) file is open. 
If the dune file is missing, a new dune file is opened in a draft (non-saved) mode. 
The PR is based on #498 
The dune rpc is coming and can replace the implementation, but the code innocuously small, so it shouldn't be a big deal. 
Without this command, I do `cmd+p`, type 'dune' and have to remember which library I'm in to disambiguate among many other dune files

New command: open "current" 'dune' file 

---

.github/workflows/main.yml

Disable dune cache in GitHub Actions workflow

---

README.md

The mentioned keyboard shortcut for opening the command palette was missing a `shift`.

Fix command palette keys in README

---

CHANGELOG.md
README.md
package.json
src/bindings/node/node.ml
src/bindings/node/node.mli
src/cmd.ml
src/cmd.mli
src/extension_commands.ml
src/extension_commands.mli
src/extension_consts.ml
src/extension_instance.ml
src/extension_instance.mli
src/platform.ml
src/platform.mli
src/repl.ml
src/repl.mli
src/terminal_sandbox.ml
src/terminal_sandbox.mli
src/vscode_ocaml_platform.ml
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

This PR adds a code evaluation feature that sends selected expressions to the REPL when pressing `Shift+Enter` (or selecting "Evaluate Expression" in the editor menu).
The REPL is provided with Utop and is instantiated using `dune utop`, so this feature depends on both dune and utop to be available in the user's sandbox.
Closes https://github.com/ocamllabs/vscode-ocaml-platform/issues/452
Closes https://github.com/ocamllabs/vscode-ocaml-platform/issues/490
**TODO**

Add Utop integration

---

src/switch_impl_intf.ml

The extension was failing with `ocaml-lsp` master after `ocaml-lsp` moved to "structured" representation for the request params [PR](https://github.com/ocaml/ocaml-lsp/commit/ad6d413e143e70b57c69660c37ef64119272418e ). 
`switchImplIntf` & `inferIntf` should send `[uri]` (a string list) not `uri` (a string). This PR does exactly that.

switchImplIntf & inferIntf use structured json requests

---

.github/workflows/main.yml
package.json

Closes #536 
Automatically adds the built VSIX file after a release is made. 
Uses [alexellis/upload-assets](https://github.com/alexellis/upload-assets) instead of [actions/upload-release-asset](https://github.com/actions/upload-release-asset) for globbing support.

Add VSIX file to github release in CI

---

CHANGELOG.md
README.md
src/bindings/node/node.ml
src/bindings/node/node.mli
src/bindings/node/node_stub.js
src/cmd.ml
src/dune_formatter.ml
src/dune_task_provider.ml
src/esy.ml
src/esy.mli
src/extension_commands.ml
src/extension_instance.ml
src/extension_instance.mli
src/ocaml_windows.ml
src/ocaml_windows.mli
src/opam.ml
src/opam.mli
src/sandbox.ml
src/sandbox.mli
src/toolchain.ml
src/toolchain.mli
src/vscode_ocaml_platform.ml
vscode/interop/interop.ml
vscode/interop/interop.mli
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

This PR adds a popup to install missing tools (`ocamllsp` and `ocamlformat` for now) when they are not found in the user's sandbox.
It installs the tools from source for now, which is time-consuming, so we'll want to use something like `opam-tools`, but I figured it was good enough for a first version, and we most likely want to use it as a fallback anyways.
Not ready for review yet, but I wanted to get some early feedback on the approach.
**TODO**
Fixes #294
Fixes #361
Fixes #353

Automatic installation of missing binaries

---

CHANGELOG.md
src/bindings/node/node.ml
src/bindings/node/node.mli
src/cmd.ml
src/cmd.mli
src/output.ml
src/output.mli
src/sandbox.ml
src/sandbox.mli
src/treeview_sandbox.ml
src/treeview_switches.ml

Displays the output of shell commands in a (more) user-friendly way:
The output channel is updated as the process writes to stdout, unlike the JSON logging which has to wait for the process to complete. 
The package management commands in the activity tab (add/remove package or switch) will automatically focus on the output channel.
The effect of this feature is that users will be able to see the progress of installing/modifying their sandbox, whereas previously there would only be an infinitely-loading notification. This is especially useful when adding packages with a lot of dependencies that take a long time to install.

Display shell command output 

---

CHANGELOG.md
syntaxes/ocaml.json

Previously, float literals with a trailing decimal point were highlighted as integers and a field accessor. 
| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/110253351-ba95a000-7f3e-11eb-91f4-b511072c6edd.png) | ![after](https://user-images.githubusercontent.com/25037249/110253364-c41f0800-7f3e-11eb-8473-cf71e783c0e1.png) |

Fix highlighting of float literals with a trailing decimal point

---

.vscodeignore

Closes #549 
The last update to the `vscode-languageclient` dependency added transitive dependencies which were being ignore by `vsce package`, breaking the extension at runtime.
I was originally going to update the `.vscodeignore` exclusions with the following:
<details>
<summary>node_modules exclusions</summary>
```
!node_modules/balanced-match/**
!node_modules/brace-expansion/**
!node_modules/concat-map/**
!node_modules/lru-cache/**
!node_modules/minimatch/**
!node_modules/semver/**
!node_modules/vscode-jsonrpc/**
!node_modules/vscode-languageclient/**
!node_modules/vscode-languageserver-protocol/**
!node_modules/vscode-languageserver-types/**
!node_modules/yallist/**
````
</details>
but after further investigation it seems that `vsce` already removes dev dependencies from …

Remove node_modules from vscodeignore

---

CHANGELOG.md
src/import.ml
src/treeview_sandbox.ml
src/treeview_switches.ml

Removing a switch or package is currently done without a confirmation box. Users could accidentally uninstall a package or switch and have to wait a long time to reinstall everything they need.
A simple confirmation dialog (using `showInformationMessage`) should be sufficient to avoid accidental removals.

Ask for confirmation when removing opam packages or switches

---

CHANGELOG.md
package.json

Closes #564
The META.* pattern interfered with syntax highlighting for other file types.

Stop automatically highlighting META.* files

---

CHANGELOG.md
src/extension_instance.ml

Closes #579 
Using map instead of bind with no type annotation was causing the error message to be ignored. Using a normal promise (not a result promise) is simpler.

Fix showing error message if ocaml-lsp is missing

---

Makefile
src/dune

Previously the sources were not mapped correctly in stack traces because sourcemaps are disabled by default in js_of_ocaml release mode.
Changes:
- `dune build src/vscode_ocaml_platform.bc.js` instead of `dune build @all` because `@all` unnecessarily copies the entire directory to `_build`.
- `--sourcemap` instead of `--sourcemap=external` because `external` does not include the `sourceMappingURL` in the generated JS.
- `--sources-content=false` because the generated JS is not being used in a debugger.
-  Clear the dist folder in `make clean`.
- `--source-map` in Js_of_ocaml flags because it is disabled for `--release`.
- `--pretty` so proper function names appear in stack traces.
It seems that this has to be enabled because other combinations of flags result in `TypeError: s.toUtf16 is …

Fix sourcemap generation

---

src/bindings/node/node.ml
src/bindings/node/node.mli
src/cmd.ml
src/import.ml

Sometimes the process sends an `error` event which has to be handled or the extension stops working.
Also, the `signal` argument of the `close` event seems to not be passed to the handler when there was an `error` event.

handle childprocess error

---

src/cmd.ml
src/cmd.mli
src/dune_formatter.ml
src/dune_task_provider.ml
src/extension_instance.ml
src/opam.ml
src/opam.mli
src/sandbox.ml
src/sandbox.mli

* Tweaks to simplify the API and keep our mli's tidier
* Removal of `which`. It is not guaranteed to exist in minimal environments such
as nix.

Remove `which` and other cleanups

---

src/vscode_ocaml_platform.ml
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

I had this commit as part of #640 , but since I'm not sure we're going further with the approach of #640, decided to create another PR. 
The bindings aren't full, but were somewhat tricky to get right (at least for me as a newbie to ojs). 
Fixed a "deprecated" warning along the way.

Add some bindings to vscode diagnostics manipulation

---

.github/workflows/main.yml
Makefile

separate `make build` and `make release-build` to 
- get faster builds and `make install`
- get warnings as errors
I grepped `release` to see whether releasing code relies on `build` target but couldn't figure out for sure, so if I'm missing something let me know.

Makefile for faster development

---

CHANGELOG.md
package.json
src/custom_requests.ml
src/extension_commands.ml
src/extension_consts.ml
src/import.ml
src/ocaml_lsp.ml
src/ocaml_lsp.mli
vscode/vscode/vscode.ml
vscode/vscode/vscode.mli

Uses a custom request in ocamllsp to jump around holes. This should allow to eliminate too tight coupling with diagnostics, which caused problems when we want to jump to the first hole in a destructed code.

Jump to holes ocamllsp typed holes

---

CHANGELOG.md
package.json
src/dune_task_provider.ml
src/extension_instance.ml
src/ocaml_windows.ml
src/repl.ml
src/sandbox.ml
src/settings.ml
src/settings.mli
src/terminal_sandbox.ml

Main goal of the PR: 
- Pass `process.env` to ocamllsp
- Add a user config to indicate "extra" environment variables to pass to ocamllsp on launch; this should be helpful to tweak (ocamllsp/merlin) log/profiling/memtrace file configs. (such a config also exists in `Rust Analyzer` for similar purposes)
I used this configuration to play with [landmarks](https://github.com/LexiFi/landmarks) to profile ocamllsp. Click on `Details` to read more about this.
<details>
I used the following config
```
"ocaml.server.extraEnv": {
"OCAML_LANDMARKS": "on,auto,allocation,output=./ocaml_lsp.profiling_data"
},
```
for the extension. 
One also needs to pin `landmarks` master and `make install` ocamllsp with env `OCAML_LANDMARKS=auto` (see the landmarks docs for more info -- this is my first time using …

Pass process environment variables (+ extra) to OCaml-LSP (using a workspace configuration)

---

.ocamlformat
fixtures/sample-esy/bin/SampleEsyApp.ml
src/cmd.ml
src/sandbox.ml
src/settings.mli

This PR is related to #666, since it introduces `ppxlib`. 
This change will be needed since `ocamlformat.0.18.0` used `ocaml-migrate-parsetree` in pair with `ppxlib`s' internal API (`Ppxlib_ast__.Versions.OCaml_408`) that will change in the the upcoming release of `ppxlib` making it incompatible. 
The `0.19.0` [drops](https://github.com/ocaml-ppx/ocamlformat/commit/448ac7c1496e2a6e83d63a7bcd9cf4e35bb2b1fb) the dependency and is therefore compatible.

Bump ocamlformat version from 0.18.0 to 0.19.0

---

DEVELOPING.md
src/bindings/node/node.ml
src/bindings/node/node.mli
src/opam.ml
src/path.ml
src/path.mli
src/settings.ml

* External Opam switches (aka local switches) often were not visible to
the extension because of the case mismatch between the switch path as
reported by `opam switch list` and the workspace folder path reported by
VS Code
* ${pathSeparator} adds a standard VS Code variable which lets VS Code
projects open portably on Windows or Unix
---
Also included a DEVELOPING.md containing slightly reverse-engineered instructions.

Windows case-insensitivity

---

CHANGES.md
package.json
src/extension_commands.ml
src/extension_consts.ml

> Add commands `Show OCaml Language Server Output`,
`Show OCaml Platform Extension Output`, and `Show OCaml Commands Output`
This should make it easier for users to see problems for themselves and tell us if they see something strange in the output such as exceptions in case of ocaml-lsp. 
The next PR will document these new commands

Add commands to show output for ocaml-lsp, the extension, and commands

---

CHANGES.md
src/opam.ml

Modified the command to set the `--set-switch` flag. Fixes (#655). @tmattio @mnxn please review

Modified the command to set the `--set-switch` flag

---

.github/workflows/changelog.yml
.github/workflows/main.yml
.ocamlformat

It currently fails to parse the `ocamlformat` version due to the comment added in https://github.com/ocamllabs/vscode-ocaml-platform/pull/746

ci: fix lint-fmt job

---

CHANGES.md
package.json
src-bindings/vscode/vscode.ml
src-bindings/vscode/vscode.mli
src/ast_editor.ml
src/cm_editor.ml
src/cm_editor.mli
src/dune
src/vscode_ocaml_platform.ml

This PR adds a new custom editor that shows info about `.cm(t, i, ti, o)` and `.bc` files. It uses the `ocamlobjinfo` behind the scene.
I didn't test it with `.bc` files because I don't know how to generate these files 😅 
Question: it looks like `ocamlobjinfo` also supports `.cmx`, `.cmxa`, `.cma`, `.cmxs`. Should we also add support for them?
Partially implements #505

support cm* files

---

README.md

There is a section in the readme referencing using ReasonML/Ocaml syntax in ReScript. I was told that specific use case is no longer supported and it could be helpful for the (few) users still stuck doing that trying to migrate off reason-language-server. I also added a workaround using Melange which allows usage of ocaml-lsp-server while still compiling to JS. The wording around it was carefully chosen to try to avoid any confusion/conflict between Rescript and Melange.

Update instructions surrounding ReasonML/OCaml + Rescript/Bucklescript Syntax Support.

---

src-bindings/vscode_languageclient/vscode_languageclient.ml
src-bindings/vscode_languageclient/vscode_languageclient.mli
src/extension_commands.ml
src/extension_instance.ml

comes in pair with https://github.com/ocaml/ocaml-lsp/pull/559
Some thoughts:
1. I think this was one of the last things I wanted to do before cutting a release for the extension. 
1.1. I think some testing would be nice, but few people use the master version, so we can release and then release again if there're problems reported
1.2. Could someone shed some light on how to cut a release? 
2. It would be nice to have a ppx to generate `of_/to_json` code. Doing that manually is wrong in many ways. It would be nice to reuse yojson ppxes but then we need to switch to using yojson ?

Fix jump to hole on destruct/construct to jump only within new generated text

---

CHANGES.md
src/extension_commands.ml
src/extension_instance.ml
src/ocaml_lsp.ml
src/ocaml_lsp.mli

Only notify users when all of the following conditions hold:
* The running version of ocamllsp is "official". We don't offer
suggestions for development versions.
* We know something about the user's version ocamllsp. If the version
isn't recognized by us, we do not second guess the user.
* We are certain the user is able to upgrade to a newer version. If the
user is forced to an older version of lsp, we allow him to use the
plugin without notifications.

fix: remove intrusive version checking

---

CHANGELOG.md
syntaxes/dune-project.json
syntaxes/dune-workspace.json
syntaxes/dune.json
test/fixtures/dune

The general dune syntax rules were duplicated between 3 files. This PR makes it so the `dune-project` and `dune-workspace` syntaxes reuse the general rules from the `dune` syntax.
Additionally, it fixes the incorrect highlighting in variables mentioned in https://github.com/ocamllabs/vscode-ocaml-platform/pull/742#issuecomment-1027296414 and adds a couple of missing variables.

Unify and improve general dune syntax

---

.github/workflows/main.yml

Should fix
```bash
Run opam depext --install ocamlformat=$(awk -F = '/version=/{print $2}' .ocamlformat)
opam: option `--resolve': invalid element in list
(`ocamlformat=0.[20](https://github.com/ocamllabs/vscode-ocaml-platform/runs/5211851399?check_suite_focus=true#step:4:20).1,4.13.1'): Invalid character in package name
"4.13.1"
Usage: opam list [OPTION]... [PATTERNS]...
Try `opam list --help' or `opam --help' for more information.
Command failed: opam --cli=2.1 list --readonly --external '--resolve=ocamlformat=0.20.1,4.13.1' returned 2
Error: Process completed with exit code 2.
```

ci: fix lint-fmt

---

src/ocaml_lsp.ml

https://github.com/ocamllabs/vscode-ocaml-platform/discussions/868#discussioncomment-2182588
Would that make sense to add a button to install the package? There's a [function for that in `Sandbox`](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/src/sandbox.ml#L573) so that shouldn't be much work I guess.

fix: improve outdated ocaml-lsp-server message

---

CHANGELOG.md
syntaxes/ocaml.interface.json

Closes #905 
The external syntax highlighting will now terminate if it finds a `]` after a string.

Fix external syntax highlighting for embedded ocaml source in comments

---

dune-project
src/ppx_tools/traverse_ast.ml
src/ppx_tools/traverse_ast2.ml
vscode-ocaml-platform.opam

- upgrade ppxlib to 0.26.0
0.26.0 has breaking API changes, so we set the required version of Ppxlib to >= 0.26.0
- fix CI failures: upper bound ocaml compiler and dune version
- dune 3.0 complains about `--pretty` flag being passed to `js_of_ocaml link` because we have `(lang dune 2.7)` (dune doesn't complain on lang 3.0 about `--pretty`); see https://github.com/ocaml/dune/issues/5563
(this PR is a result of PR #919 being split in several)

upgrade ppxlib to 0.26.0

---

dune-project
vscode-ocaml-platform.opam
vscode.opam

Since commit 93e88b7799830dc4711cf6b61957715460eac1fa support for let*/let+ punning introduced in ocaml 4.13 is required to compile the repository. 
Here I propose to bump ocaml version lower bound but an alternative fix could be to reformat for 4.11. 
Feel free to merge or close this PR.

Require ocaml >= 413 to compile

---

CHANGELOG.md
languages/ocaml.json

Old behavior :
New behavior :
Can we add the feature for it ?

Add arrays to auto closing pairs

---

src/repl.ml

I think that this wrong name makes the option unavailable.

Fix `useUtop`

---

CHANGELOG.md
src/ast_editor.ml
src/import.ml

reveal ast node command can now open an ast explorer and reveal the node in the newly opened explorer
fixes #961

fix #961: reveal ast node can now open ast explorer

---

.gitignore
.ocamlformat-ignore
.prettierignore
CHANGELOG.md
Makefile
package.json
src-browser/dune
src-browser/vscode_ocaml_platform_web.mli
src/dune

This is the ground work for https://github.com/ocamllabs/vscode-ocaml-platform/issues/733
Basically the only requirement to have the extension listed as web-compatible is to add a `"browser": ...` field in `package.json`. 
Obviously the script in `"main": "./dist/vscode_ocaml_platform.bc.js"` is not web-compatible as it uses various nodejs apis. 
This PR adds the plumbing to generate a `vscode_ocaml_platform_web.bc.js` script that would act as the web version of the extension. Currently it's empty as no commands are implemented. Instead they are all disabled in the manifest file using `"enablement": "!virtualWorkspace"`.
So what remains working is syntax highlighting, which is a nice thing to have when inspecting code from the web (using github.dev for example).

Minimal support for web

---

CHANGELOG.md
syntaxes/ocaml.interface.json
syntaxes/ocaml.json

Currently `let x : t` colors correctly but the spaceless version `let x:t` does not color `x`.
This PR fixes that.

Fix syntax highlighting for let bindings

---

CHANGELOG.md
src/settings.ml

`${firstWorkspaceFolder}` can now be used as a placeholder variable in configuration files to avoid specifying a folder name with `${workspaceFolder:name}`. When VSCode only has one folder open, `${firstWorkspaceFolder}` will correspond to that folder.

Add support for `${firstWorkspaceFolder}` as a placeholder variable in configuration files

---

CHANGELOG.md
README.md
package.json
src/ocaml_windows.ml
src/ocaml_windows.mli
src/opam.ml

Resolves #977
This PR allows the extension to automatically use the Diskuv OCaml Windows executables from the PATH when `ocaml-env` does not exist.

Only use ocaml-env if it is available

---

.github/workflows/main.yml

This check always fails because we can't install `opam-dune-lint` because it conflicts with our deps.

remove `lint-opam` CI check

---

CHANGELOG.md
src-bindings/vscode/vscode.ml
src-bindings/vscode/vscode.mli
src/ast_editor.ml

* constructor fn for `WebviewOptions` incorrectly indicated that all fields were mandatory, while it's the opposite
* fields in `WebviewOptions` are also readonly in `vscode.d.ts`, which is not indicated in the vscode API webpage
* given the above, the previous code was incorrect to change fields of `WebviewOptions`
* the fix for ast-explorer comes from enabling the scripts earlier - so change of location of code is important for the fix
fixes #1046

fix ast-explorer enable-scripts

---

CHANGELOG.md
package.json

Fixes #1054 
Ordering notation:
https://code.visualstudio.com/api/references/contribution-points#Sorting-inside-groups

Reorder sandbox buttons

---

.github/workflows/main.yml

Currently, the Windows build is failing.
This PR attempts to fix it with a workaround described here:
https://discuss.ocaml.org/t/sunsetting-opam-repository-mingw/11632#whats-happening-right-now-1

Update Windows Github workflow

---

nix/default.nix
nix/opam-selection.nix
shell.nix

Currently, Nix build uses Node in version 14.x. It fail with following message:
```
error: Package ‘nodejs-14.21.3’ in /nix/store/wdi2jyp0d556jhyriaksrmfx4a798nhr-source/pkgs/development/web/nodejs/v14.nix:11 is marked as insecure, refusing to evaluate.
Known issues:
- This NodeJS release has reached its end of life. See [https://nodejs.org/en/about/releases/.](https://nodejs.org/en/about/releases/)
```
I tried to bump it to 16.x, but it fails as well. The lowest version that works is 18.x, which is current Node LTS.
This PR is the smallest amount of work that makes Nix build go green.
In separate PR we should consider bumping Node for other workflows as well.

Bump node for Nix

---

nix/default.nix

When trying to run `nix-shell` on macOS I get following error:
```
> src/fsevents/fsevents_stubs.c:16:10: fatal error: 'CoreServices/CoreServices.h' file not found
> #include <CoreServices/CoreServices.h>
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> Command failed.
For full logs, run 'nix log /nix/store/xp20z29pj9gv78jm3326sis3lyngwrdm-dune-3.7.1.drv'.
```
This PR fixes it

Fix nix-shell for macOS

---

.github/workflows/changelog.yml
CONTRIBUTING.md

The same job is already used in ocaml-lsp. Let's add it to vscode plugin as well.

Add changelog check to CI

---

.github/workflows/main.yml

This PR addresses following CI warnings:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: esy/github-action@v1, actions/upload-artifact@v2, GabrielBB/xvfb-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
Bumped upload-artifact and xvfb-action. Esy cannot be bumped, because it's hardocoded to 12. I will create a PR to esy to change it

Bump github actions

---

.github/workflows/main.yml
.github/workflows/nix.yml

This solves a problem of running the same job twice:
Source:
https://github.com/ocamllabs/vscode-ocaml-platform/pull/1135

Run CI once on PR opening

---

CHANGELOG.md
package.json
src-bindings/vscode/vscode.ml
src-bindings/vscode/vscode.mli
src-bindings/vscode_languageclient/vscode_languageclient.ml
src-bindings/vscode_languageclient/vscode_languageclient.mli
src/extension_instance.ml
src/settings.ml
src/settings.mli
src/vscode_ocaml_platform.ml

ocamllsp has settings for codelens and extendedHover. They can be changed dynamically. And they are now critical since by default the codelens are disabled without an easy way to restore them. This is an effort to support those settings in vscode.
https://github.com/ocaml/ocaml-lsp/blob/ca325e770100adca845a563cad7eaffa75480fbc/ocaml-lsp-server/docs/ocamllsp/config.md?plain=1#L1-L25
https://github.com/ocaml/ocaml-lsp/pull/1134
This work is paid for by Ahrefs.

Support lsp server settings

---

CHANGELOG.md
src/extension_instance.ml
src/repl.ml
src/terminal_sandbox.ml
src/terminal_sandbox.mli

This just grabs the preserve focus part of this PR https://github.com/ocamllabs/vscode-ocaml-platform/pull/951 which seems stalled. I don't feel strongly about the rest of that PR, but loosing focus on the editor every time i use the repl Is a massive pain and basically just feels like a bug. So I'd love to get that little part merged :).

Preserve focus when sending to repl

---

CHANGELOG.md
languages/ocaml.json

Right now if you write a let expression where the identifier has a single quote in it, the indentation level won't be increased. Then when you write an `in` keyword, the level will be decreased resulting in something like:
```ocaml
let test =
let a' =
2
in
a' + foo
```
The same thing applies for `let*` and `let+` expressions:
```ocaml
let test =
let* a =
bar
in
ret (a + foo)
```
This PR modifies the indentation regex so that all the binding operators for `let` and `and` are matched as well as single quotes in the identifier:
```ocaml
let test =
let* a' =
bar
in
ret (a' + foo)
```

Indentation increase for more let expressions

---

.github/dependabot.yml
CHANGELOG.md
Makefile
package.json
yarn.lock

VScode v1.82.0 and later uses Electron v25, which uses Node.js v18 internally[^1], so we should be able to safely raise the ECMAScript version[^2].
[^1]: https://github.com/ewanharris/vscode-versions
[^2]: https://node.green

VScode 1.82.0

---

src-bindings/interop/interop.ml
src-bindings/interop/interop.mli
src-bindings/node/node.mli
src-bindings/polka/polka.mli
src-bindings/vscode/vscode.ml
src-bindings/vscode/vscode.mli
src-bindings/vscode_languageclient/vscode_languageclient.mli
src/cm_editor.ml
src/treeview_sandbox.ml

Ever since https://github.com/LexiFi/gen_js_api/pull/166, many of the modules that are defined in our `interop` library have become redundant.
In this PR, I replace the custom modules with those available from `gen_js_api`, where possible. For the generic function bindings, it was also possible to have `gen_js_api` generate the module-handling code.
I removed the previous `generic` type aliases since they make the code more confusing for very little added convenience. After doing this, I realized most of the functor applications in the bindings are unnecessary since they are only needed to call methods.
Eventually, I would still like to use [ts2ocaml](https://github.com/ocsigen/ts2ocaml), but these changes make our current bindings simpler for the time being.

Simplify gen_js_api bindings

---

README.md

Previously, official GHA badges were not allowed to be used, but that seems to have been fixed already now: https://github.com/microsoft/vscode-vsce/issues/389#issuecomment-643961423

Fix the build status badge

---

CHANGELOG.md
src-bindings/vscode_languageclient/vscode_languageclient.ml
src-bindings/vscode_languageclient/vscode_languageclient.mli
src/extension_instance.ml

Fixes #1261 
Version 9 of vscode-languageclient renamed the `dispose` field to `clear`. The extension was crashing after the language server restarts and the undefined `clear` function is called.

Fix extension crashing after restarting the language server

---

package.json
tests/suite/basic/index.js
tests/suite/basic/problems.test.ts
tests/suite/esy/index.js
tests/suite/esy/languageId.test.ts
tests/suite/opam/index.js
tests/suite/opam/languageId.test.ts
tsconfig.json
yarn.lock

It's not as easy as it sounds to make the entrypoints as TypeScript, and the benefits aren't as big, so I'm keeping them as plain JavaScript. By making the test file itself TypeScript, we can gain benefits such as code completion. And since they are processed through SWC, there is very very little overhead.

Run TypeScript tests with swc

---

CHANGELOG.md
src/switch_impl_intf.ml

I tried including `re` extensions in the switch impl/intf functionality, and it works perfectly fine, including Melange projects:

support switch between impl and intf in reason

---

CHANGELOG.md
README.md

This wasn't working for me, and I eventually found this https://github.com/ocamllabs/vscode-ocaml-platform/issues/1222#issuecomment-1732451170
```
{
"ocaml.sandbox": {
"kind": "esy",
"root": "${firstWorkspaceFolder}"
}
}
```
Is the correct way to do this by default

Fix esy sandbox setup

---

Makefile

To work around an issue with [`vsce` not being compatible with `yarn` > 1](https://github.com/microsoft/vscode-vsce/issues/517#issuecomment-1853832670). Also similar to what we do in `package.json`
https://github.com/ocamllabs/vscode-ocaml-platform/blob/15568114a7924854a535a680ec13bb91f002643f/package.json#L30

pass --no-dependencies to vsce package

---

CHANGELOG.md
src-bindings/node/node.ml
src-bindings/node/node.mli
src/extension_instance.ml

Extensions may mutate the `process.env` this is especially true for https://github.com/direnv/direnv-vscode which will reset every property.
But currently the `process.env` is copied once during the load of the extension, making so that OCaml Platform and direnv are incompatible or need to be hacked around.

recompute env dict on every command

---

CHANGELOG.md
src/extension_instance.ml
src/extension_instance.mli
src/vscode_ocaml_platform.ml

Currently the extension doesn't notify the LSP of configurations, this means that since https://github.com/ocaml/ocaml-lsp/pull/1134 codelens are disabled whenever you start VSCode, even if you explicitly opt-in to codelens.
This is also true for disabling dune diagnostics like #1320.
This PR enables codelens again by default, as they're enabled in the manifest of the extension, I feel like this may be desirable anyway so I didn't change it, but if the extension wants to disable it by default, is just a matter of changing this https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/package.json#L267
- #1320

Notify LSP of workspace config when starting

---

CHANGELOG.md
package.json
src-bindings/vscode_languageclient/vscode_languageclient.ml
src-bindings/vscode_languageclient/vscode_languageclient.mli
src/extension_instance.ml
src/extension_instance.mli
src/settings.ml
src/settings.mli
src/vscode_ocaml_platform.ml

I would like to disable dune diagnostics as mentioned in 
https://github.com/ocaml/ocaml-lsp/pull/1221
This also shines light in a bug, currently "vscode-ocaml-platform" doesn't push the configs when starting the server, making so that the config is only pushed when you change them. I will fix this in a future PR.
- https://github.com/ocaml/ocaml-lsp/pull/1221

Add `ocaml.server.duneDiagnostics` to disable dune diagnostics reporting

---

src/extension_instance.ml

We always pass these arguments, so there's no need for "optionality"

refactor: more optional argument removal

---

src-bindings/vscode_languageclient/vscode_languageclient.ml
src-bindings/vscode_languageclient/vscode_languageclient.mli
src/extension_instance.ml
src/ocaml_lsp.ml
src/ocaml_lsp.mli

These aren't any general purpose bindings, they should live in the
extension

refactor: move ocamllsp settings to extension

---

CHANGELOG.md
package.json
yarn.lock

Prepare 1.16.0

---

CHANGELOG.md
syntaxes/ocaml.json

Ocamldoc comments start with only two stars: https://v2.ocaml.org/manual/ocamldoc.html#s:ocamldoc-comments.
Previously, any comment starting with two stars or more was marked as ocamldoc. This PR fixes that, so comments starting with more stars are no longer marked as ocamldoc.
This is visible when using a theme that as a different color for doc comment, like [mine](https://github.com/dlesbre/vscode-embers), but also when putting ocamldoc syntax like `@tags` or `[code]`, which change color in doc comments but not in non-doc comments.

Fix improper coloring of ocamldoc comments

---

CHANGELOG.md
syntaxes/ocaml-markdown-codeblock.json
syntaxes/reason-markdown-codeblock.json

This fixes #1288. I copied code structure from https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example. The short description of this fix is: "don't inject `ml <code>` in an md codeblock, instead inject ```` ```ml\n <code>\n``` ```` in md directly".

Fix md code block bug

---

CHANGELOG.md
syntaxes/ocamldoc.json

A few ocamldoc markup had syntax color, but most didn't. This PR adds color to most markup, using the similar markup in markdown for the textmate scope. For reference, I used the following:
- ocamldoc syntax reference: https://v2.ocaml.org/manual/ocamldoc.html#s%3Aocamldoc-comments
- odoc syntax reference: https://ocaml.github.io/odoc/odoc_for_authors.html
- odoc differences with ocamldoc: https://ocaml.github.io/odoc/ocamldoc_differences.html
Before this PR, only few constructs had syntax coloring:
- `@tags`
- `[inline code]` (note that inline code is rendered using ocaml's syntax highlighting, and not semantic highlighting. Depending on theme, the colors may be very different from the rest of the file).
I added the following:
- `{b bold]` `{1 heading]` `{i italic]` `{e emph}` (colored …

Add syntax color to ocamldoc markup

---

CHANGELOG.md
package.json
yarn.lock

Prepare 1.17.0

---

src/import.ml

This PR removes the hack added to avoid throwing uncaughtException, since vscode can handle uncaughtException gracefully after 1.86

Remove exception Hack

---

src-bindings/interop/interop.ml
src-bindings/vscode/vscode.ml
src-bindings/vscode/vscode.mli
src/cm_editor.ml

As mentioned in https://github.com/ocamllabs/vscode-ocaml-platform/pull/1402#pullrequestreview-1916685023, gen_js_api has included conversion functions for the `unit` type for a while. That means we can reduce the use of our `Js.Unit.t` type and reference the `unit` type directly instead.
There are still a couple of remaining reference to `Js.Unit` where the module is used as an argument to a functor. gen_js_api doesn't have a `Unit` module, so we can't replace that type of use case yet.

Reduce use of Js.Unit module

---

CHANGELOG.md
package.json
src/treeview_sandbox.ml
src/treeview_switches.ml

Fallback to the `ocaml.org` package documentation page if there is no `doc` field in the package's opam file. Note that it doesn't currently check whether the page exists on `ocaml.org`, so it may return a `404` error.
https://github.com/ocamllabs/vscode-ocaml-platform/assets/5595092/20b71a45-c7ab-4115-be16-f6f75ea63e25

fallback to ocaml.org documentation page

---

.github/workflows/main.yml

https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/

Use `macos-latest` again

---

CHANGELOG.md
syntaxes/ocamldoc.json

Add syntax color to:
- odoc tables (added in odoc 2.3), 
- odoc headings with labels (`{1:label heading}`) 
- code block with attributes (used by [mdx](https://ocaml.org/p/mdx/latest)).
- also color `{@ocaml attr[` blocks as ocaml instead of verbatim (previously only `@{[` block were colored as ocaml).
Here is an example test comment:
```ocaml
(**
{1:label section}
{table
{tr
{td {b hello}}
{th heading}
}
}
{t
| hello | there | header | text |
| --- | :-- | :---: | --:
| a | b | c | d
}
{@ocaml skip[
let x = 5
]}
{@notocaml someattribute[
this is just colored as verbatim
]}
*)
```

Odoc markup

---

CHANGELOG.md
syntaxes/dune-project.json

This change is needed for packages such as `ISO8601` 🤷‍♂️

Fix syntax for `dune-project.package.(depends|conflicts|depopts)`

---

CHANGELOG.md
syntaxes/dune-project.json

This is not mentioned in the dune documentation somehow, but it's a valid syntax and is used here: https://github.com/ocamllabs/vscode-ocaml-platform/blob/523baffdc34eea32dd7b07eed49546fd71d0a830/dune-project#L27

Add syntax for `dune-project.package.allow_empty`

---

src/custom_requests.ml
src/custom_requests.mli
src/extension_commands.ml

cc @voodoos 
This PR refactors `Type_enclosing` custom request to a uniform structure which will be adopted by subsequent custom request implementations as seen in #1619

Refactor type enclosing

---

CHANGELOG.md
src/extension_instance.ml

If you're using the dune developer preview then ocamlc won't be globally installed. It's a bit offputting to have the plugin pop up with an error every time vscode starts, especially since the plugin seems to work fine without it. This downgrades it to a warning and adds an "Ignore" button.

Make it a warning if ocamlc is missing

---

CHANGELOG.md
src/extension_instance.ml

This is needed when dune is managing the installation of ocamllsp, as it needs to determine which version of ocamllsp to run by looking in the current project's lockdir.

Run ocamllsp -version in workspace dir

---

CHANGELOG.md
package.json
src/custom_requests.ml
src/custom_requests.mli
src/extension_commands.ml
src/extension_consts.ml
src/ocaml_lsp.ml
src/ocaml_lsp.mli
src/treeview_commands.ml

This PR implements the [Jump Custom Requests](https://github.com/ocaml/ocaml-lsp/pull/1374).
Jump results are displayed in a [QuickPick](https://code.visualstudio.com/api/ux-guidelines/quick-picks) component where upon selection, the jump is made to the selected target.
This command can be triggered from the command pallet or with the keyboard binding `Alt +J`
- `Ocamllsp warning`: If `ocamllsp` is not running at the time the command is invoked, this notification is displayed.
- `No support for requests`: If the version of ocamllsp doesn't publish the `ocamllsp/jump` capability then this notification is displayed. 
One command is published `ocaml.jump` which triggers the process.
https://github.com/user-attachments/assets/84734598-c322-407f-960e-3649b05543a5
- QuickPick : …

Jump Custom Request Client Implementation

---

CHANGELOG.md
README.md
package.json
src-bindings/vscode/vscode.ml
src-bindings/vscode/vscode.mli
src/custom_requests.ml
src/custom_requests.mli
src/extension_commands.ml
src/extension_consts.ml
src/import.ml
src/ocaml_lsp.ml
src/ocaml_lsp.mli
src/treeview_commands.ml
src/treeview_help.ml
src/treeview_sandbox.ml
src/treeview_switches.ml

This PR implements the [Search By Type or Polarity Custom Requests](https://github.com/ocaml/ocaml-lsp/pull/1369).
The UI uses a [QuickInput](https://code.visualstudio.com/api/references/vscode-api#QuickInput) component which provides a textbox for the user to enter the search query. 
The results are displayed in a [QuickPick](https://code.visualstudio.com/api/ux-guidelines/quick-picks) component where upon selection, the value is inserted into the document at the cursor location.
The QuickInput and QuickPick components are ideal for this use case given they are lightweight and offer robust performance as compared to webviews. 
They also offer easy navigation and are suitable for both mouse and keyboard usage.
The entire workflow is done in 3 steps:
The command can be triggered using one …

Search By Type or Polarity

---

CHANGELOG.md
package.json
src/extension_commands.ml
src/extension_consts.ml
src/settings.ml
src/settings.mli
src/treeview_commands.ml

This PR implements navigation of typed holes.
Results are displayed in a [QuickPick](https://code.visualstudio.com/api/ux-guidelines/quick-picks) component where upon selection, the cursor is moved to the selected typed hole.
This command can be triggered from the command pallet "Navigate to different typed holes"
- `Ocamllsp warning`: If `ocamllsp` is not running at the time the command is invoked, this notification is displayed.
- `No support for requests`: If the version of ocamllsp doesn't publish the `ocamllsp/typedHoles` capability then this notification is displayed. 
One command is published `ocaml.navigate-typed-holes` which triggers the process.
https://github.com/user-attachments/assets/b14aa44e-ea00-494c-9164-83464bee0f05
- QuickPick : …

Navigating Typed Holes

---

CHANGELOG.md
src/extension_commands.ml

When construct is empty, display an error message instead of an empty quickPick. 
cc @voodoos

Display message instead of empty list

---

CHANGELOG.md
package.json
src-bindings/vscode/vscode.ml
src-bindings/vscode/vscode.mli
src/ast_editor.ml
src/custom_requests.ml
src/custom_requests.mli
src/extension_commands.ml
src/extension_consts.ml
src/extension_instance.ml
src/extension_instance.mli
src/import.ml
src/ocaml_lsp.ml
src/ocaml_lsp.mli
src/output.ml
src/type_selection.ml
src/vscode_ocaml_platform.ml

This PR adds three new commands that can be used to get the type of a selection, and the ones of growing enclosings of this selection. At each step it is possible to ask for more verbose results.
The following videos show how the types of the growing selection are shown in a hover popup, with the selection growing, then shrinking, and lastly with an increased verbosity:
https://github.com/user-attachments/assets/dca1c995-45bc-45c7-adee-ce83e4dbb702
The type history is also logged to an output channel which can be configured to show up automatically and clear itself to show only the last result.
I have been through a lot of back and forth to get to this result, because it is not possible (to the extent of my knowledge) to easily disable the standard hover provider from the client side due …

New command: Type of dynamic selection

---

CHANGELOG.md
src/extension_commands.ml

This PR 
- fixes the empty list bug (displays a message rather than an empty quick pick) 
- allows the user to preview the different jump targets using the arrow keys without jumping to them.
Match first word from position of interest
https://github.com/user-attachments/assets/cda4a8af-82e5-437b-80b6-377acf9c7085
cc @voodoos @awilliambauer

Improve quick peek with highlighting in both the jump and holes commands

---

CHANGELOG.md
src/ast_editor.ml

This PR adds reasonml to ast_editor to be able to see AST and Pp
Working with both ocaml and reason
- Follow this steps: https://github.com/ocamllabs/vscode-ocaml-platform/blob/88cbda69761298bde70803d5792c90b497a4256f/CONTRIBUTING.md#L27
- On the debug view, create a `.re` file
- To see the pp you need to build it to have the `.pp.ml` file

Add reason language to ast_editor

---

CHANGELOG.md
syntaxes/ocamldoc.json

Fix a small bug in odoc syntax coloring. The math mode (`{m ...}` and `{math ... }` blocks) used to terminate at the first closing brace `}`. However, math mode uses LaTeX syntax and thus, can contain a lot of braces (eg. `2^{256}`). This PR fixes that issue.
Here is a small comment that shows the difference:
```ocaml
(**
- Inline math: {m 2^{256}+2^{128}}
- Display math:  {math
2^{256}+2^{128}
}
*)
```

Fix odoc syntax color for math block with braces

---

CHANGELOG.md
package.json

The extension assigns the key binding Alt+D to the very useful "destruct" code action, but currently the key binding doesn't do anything (also see https://github.com/ocaml/ocaml-lsp/issues/1301).
I did some digging and discovered that the definition of the key binding is passing the `destruct` kind, but ocaml-lsp actually names the kind `destruct (enumerate cases)`.
Now the keybinding is correctly mapped to the destruct action, and I also see the keys suggested in the code actions context menu:

Map Alt+D to the correct action kind in package.json

---

CHANGELOG.md
package.json
src/extension_commands.ml
src/extension_consts.ml
src/extension_instance.ml
src/extension_instance.mli
src/ocaml_lsp.ml
src/ocaml_lsp.mli
src/opam.ml
src/opam.mli
src/sandbox.ml
src/sandbox.mli
src/type_selection.ml

Currently, when `ocaml-lsp-server` is not found in a sandbox, the language server displays an error and fails to start. 
This PR improves users experience by providing a UI that asks if they will like to install or update `ocaml-lsp-server` or select another sandbox.
If the user wants to select another sandbox, a quickpick will be displayed with various switches. 
If the user decides to install `ocaml-lsp-server`, it will be installed in the background and they can continue with their activities in the editor. 
This PR will streamline the process for complete beginners and also reduce the time to terminal for experienced users who often will have to switch to the terminal to install `ocaml-lsp-server` in their sandbox.
cc @voodoos

Automatically install or update ocaml-lsp-server 

---

CHANGELOG.md
syntaxes/mlx.json
syntaxes/ocaml.json

The existing syntax support for quoted string literals was always buggy since it didn't track the IDs. See the first screenshot in #930 for an example.
Since semantic highlighting in the language server highlights these correctly now, I don't see a reason to leave the broken version in the grammar.

Remove quoted string literal highlighting from grammar

---

CHANGELOG.md
syntaxes/mlx.json
syntaxes/ocaml.json

Closes #1868
The flawed grammar + semantic highlighting was more reliable than no grammar rules and semantic highlighting.

Reintroduce quoted string literal highlighting with correct ID handling

---

CHANGELOG.md
src/extension_commands.ml
src/extension_instance.ml
src/sandbox.ml
src/sandbox.mli

This Pr no longer relies on the shim script to start ocamllsp server and rather starts it as a dune dev tool.
cc @pitag-ha

Start the ocamllsp server as a dev tool

---

CHANGELOG.md
src/treeview_help.ml

This PR adds permanently a link to the tutorials and exercises page of the ocaml.org platform.
cc @pitag-ha

Add links to ocaml tutorials

---

CHANGELOG.md
src/dune.ml
src/dune.mli
src/extension_commands.ml
src/sandbox.ml
src/sandbox.mli

Previously, wrt Dune package management we check if ocamllsp is present by checking if its found in the `dev-tools.lock` directory. 
This PR https://github.com/ocaml/dune/pull/11922 allows us to be able to check for the presence of ocamllsp in a much cleaner way `dune tools which ocamllsp`.
cc @pitag-ha

Check if ocamllsp is present the dune way

---

CHANGELOG.md
src/sandbox.ml

This PR fixes a bug on Windows that appeared in version 1.32.1.
The command for starting the LSP server was failing with exit code `-4058` (ENOENT: file or directory not found).
The bug was introduced by commit aab1308d15d0ef442f3114c391a9ad1e247e11d9 of #1925, which replaced the following code:
```ocaml
let cwd =
match Workspace.workspaceFolders () with
| [ cwd ] -> Some (cwd |> WorkspaceFolder.uri |> Uri.fsPath |> Path.of_string)
| _ -> None
in
```
with a call to `Sandbox.workspace_root ()`, defined as:
```ocaml
let workspace_root () =
match Workspace.workspaceFolders () with
| [] -> None
| [ workspace_folder ] ->
Some (workspace_folder |> WorkspaceFolder.uri |> Uri.path |> Path.of_string)
| _ ->
(* We don't support multiple workspace roots at the moment *)
None
```
The problem is that …

Use Uri.fsPath instead of Uri.path to use with Node.js filesystem APIs

---

CHANGELOG.md
src/dune.ml

When vscode is launched the platform extension tries to find all sandboxes which are available. Since we want users to be more aware of DPM, we have a notification which reads `Dune Package Management selected with dune from [dune|opam], [1.20]`. This is confusing, as it displays regardless of if the user has selected DPM or not. 
We should change the wording to `Dune Package Management is available with dune from [dune|opam], [1.20]`
cc @pitag-ha @smorimoto

Change wording of dune notifications
