ocamllabs/vscode-ocaml-platform

package.json
Taken from the reaosnml plugin
=> Add problem matcher for OCaml code

package.json, syntaxes/reason-markdown-codeblock.json
=> Add support for markdown reason blocks

package.json, yarn.lock
This allows us to execute the package script.
=> Add vsce as dev dependency

snippets/ocaml.json
=> Fix and improve snippets for OCaml

.github/workflows/workflow.yml
=> Add workflow.yml

languages/ocaml.json
=> Add indentationRules to ocaml.json

CHANGELOG.md, syntaxes/opam.json
Addresses #97
I'm not entirely familiar with the opam file format, so if I missed something, please let me know.
Comparison:
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/78398989-ee3aae00-75a8-11ea-8282-0d31677527e8.png) | ![new](https://user-images.githubusercontent.com/25037249/78398995-f1359e80-75a8-11ea-8a07-c4baef7283d1.png) |
=> Improve opam syntax

src/Cmd.ml, src/Cmd.mli, src/Extension.ml, src/Manifest.ml, src/Manifest.mli, src/Setup.ml, src/Setup.mli, src/Toolchain.ml, src/Toolchain.mli, src/import.ml, src/path.ml, src/path.mli
Use one Path module consistently
=> Remove Fpath in favor of Path

CHANGELOG.md, package.json, syntaxes/dune-project.json
_Partially_ addresses #106.
Sorry it took so long but here it is:
The `general` syntax rules will be extracted into the dune grammar once that it rewritten (soon).
=> dune-project syntax highlighting

README.md, src/esy.ml
Alternative to https://github.com/ocamllabs/vscode-ocaml-platform/pull/159 
Disabling BSB setup instead of removing it, so could be brought back after improvements.
=> Disable BSB autosetup

syntaxes/reason.json
Fixes #172 
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/80996179-40632f00-8df4-11ea-81ff-6b77682fc548.png)|![new](https://user-images.githubusercontent.com/25037249/80996187-43f6b600-8df4-11ea-8040-de540c819677.png)|
=> Fix ReasonML highlighting for nested comments

.github/workflows/workflow.yml, package.json
https://code.visualstudio.com/api/working-with-extensions/continuous-integration#automated-publishing
=> Add a publish step to GitHub Actions

package.json, yarn.lock
=> Remove uuid from dependencies

.github/workflows/workflow.yml, fixtures/sample-esy/.vscode/settings.json, fixtures/sample-esy/package.json, package.json, test/runEsyTests.js, test/suite/esy.test.js
=> Fixes e2e tests for esy

package.json, webpack.config.js, yarn.lock
I was trying to do something about webpack logs because it outputs a lot of unnecessary stuff. As a result, webpackbar seems to be a not bad option. I also added some useful plugins.
=> Tweak webpack configuration file

README.md
I tested this locally. Please try to run it on your machines. I have a couple of projects with a similar setup.
=> Simplify installation instructions for BuckleScript projects

src/DuneFormatter.ml
Fixes warnings:
> Warning 27: unused variable options.
> Warning 27: unused variable token.
=> fix unused variable warnings

CHANGELOG.md, src/path.ml, src/path.mli
This broke the esy configuration in some cases for me
=> Fix Path.parent

.vscode/launch.json
* Set outFiles correctly
* Disable other extensions when testing this extension
=> Improve launch configuration

src/Toolchain.ml, src/esy.ml, src/esy.mli
* Include error messages for manifest that failed to vaildate for some reason
* Do not read arbitrary json files
=> Improve esy sandbox discovery

src/Cmd.ml, src/DuneFormatter.ml, src/Extension.ml, src/Promise.ml, src/Toolchain.ml, src/esy.ml, src/import.ml, src/opam.ml
Low level information is now just logged instead of being presented to
the user.
=> Improve logging and error messages

src/Extension.ml, src/bindings/Vscode.ml, src/bindings/Vscode.mli
* Make command registration return disposables
* Allow to attach disposablas to the extension context
=> Improve dispose handling

src/Extension.ml, src/bindings/Vscode.ml, src/bindings/Vscode.mli
https://github.com/ocamllabs/vscode-ocaml-platform/pull/230#issuecomment-633185813
=> Stop Instance on extension dispose

CHANGELOG.md, syntaxes/ocaml.json
http://caml.inria.fr/pub/docs/manual-ocaml/locallyabstract.html
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/83097157-49929500-a05c-11ea-84d0-1fbc5c016586.png) | ![new](https://user-images.githubusercontent.com/25037249/83097249-7e9ee780-a05c-11ea-8458-8ac1538f8c42.png) |
=> locally abstract types syntax highlighting

src/bindings/Vscode.ml, src/bindings/Vscode.mli
I want to write a task provider for dune. As a first step here are some bindings to the task provider api.
https://code.visualstudio.com/api/references/vscode-api#TaskProvider
In Task, I don't know what Workspace and Global refer to. So I only handle a workspace folder for now. But I still use a variant and bs.unwrap to mark that the api is incomplete here.
https://code.visualstudio.com/api/references/vscode-api#Task
Also I didn't bind the custom execution. Only shell and process execution are supported
https://code.visualstudio.com/api/references/vscode-api#CustomExecution
If the bindings can get merged I will then provide a second PR with the dune provider itself.
=> Add taskProvider bindings

CHANGELOG.md, README.md, languages/oasis.json, package.json, syntaxes/oasis.json
=> OASIS syntax highlighting

src/bindings/Vscode.ml, src/bindings/Vscode.mli
Add bindings to show/open text documents
=> Add vscode open/show bindings

CHANGELOG.md, README.md, package.json, src/Extension.ml
Closes #224
Current behavior is to prompt the user to select a toolchain to start if no language server is running.
=> Restart command

CHANGELOG.md, languages/ocaml.json
| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/85909470-02b8cc00-b7cf-11ea-807e-35d7026e3c44.gif) | ![after](https://user-images.githubusercontent.com/25037249/85909475-064c5300-b7cf-11ea-8ed5-3db1b25cec23.gif) |
=> Fix indentation rules for let-in expressions.

CHANGELOG.md, syntaxes/ocaml.interface.json
| Old .ml | Old .mli |
| - | - |
| ![old_ml](https://user-images.githubusercontent.com/25037249/87076417-94b0d380-c1d6-11ea-905a-66c41c9133a5.png) | ![old_mli](https://user-images.githubusercontent.com/25037249/87076426-97abc400-c1d6-11ea-9c0b-7c7f99719961.png) | 
| New |
| - | 
| ![new](https://user-images.githubusercontent.com/25037249/87076439-9b3f4b00-c1d6-11ea-8879-a30ac1945f72.png) |
=> Improve highlighting of external declarations

CHANGELOG.md, syntaxes/ocaml.interface.json, syntaxes/ocaml.json
| Old | New |
| - | - |
| ![old](https://user-images.githubusercontent.com/25037249/87480979-468b3e00-c5e3-11ea-9025-1b84a0953606.png) | ![new](https://user-images.githubusercontent.com/25037249/87480988-4ab75b80-c5e3-11ea-92b6-42c1fb89af1a.png) |
=> Fix syntax highlighting of lazy bindings

.ocamlformat, src/Extension.ml, src/bindings/Node.ml
Updated to 0.15.0 in the config file.
=> Update to ocamlformat 0.15.0

CHANGELOG.md, package.json
Closes #118 
References schema from https://github.com/esy/esy-schema
=> Add esy.json schema validation

CHANGELOG.md, syntaxes/merlin.json
| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/91933907-d02fc180-ec9e-11ea-90a5-42a6be14d643.png) | ![after](https://user-images.githubusercontent.com/25037249/91933911-d2921b80-ec9e-11ea-8adf-739c7c205a0e.png) |
=> Highlight dashes in PKG names for .merlin files

CHANGELOG.md, syntaxes/merlin.json
| Before | After
| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/92022081-964ad380-ed0f-11ea-8669-26b7dc7662d1.png) | ![after](https://user-images.githubusercontent.com/25037249/92022090-9945c400-ed0f-11ea-8a91-1dae78dbd4fa.png) |
=> Improve highlighting of path elements and strings in .merlin files

README.md
Workflow for esy is missing though
=> document how to use extension on Windows

CHANGELOG.md, syntaxes/ocaml.interface.json, syntaxes/ocaml.json
| - | - |
| ![before](https://user-images.githubusercontent.com/25037249/92771802-0b418d00-f350-11ea-8c14-53c0700d7884.png) | ![after](https://user-images.githubusercontent.com/25037249/92771758-0381e880-f350-11ea-9cd7-9ee2d5fad3c8.png) |
=> Consistent binding operator highlighting in OCaml files

src/Toolchain.ml
=> Prettify sandbox names to pick

CHANGELOG.md, assets/switch-impl-intf.dark.svg, assets/switch-impl-intf.light.svg, package.json
=> add custom icons for switchImplIntf

src/Cmd.ml, src/DuneFormatter.ml, src/DuneTaskProvider.ml, src/TerminalSandbox.ml, src/Toolchain.ml, src/bindings/interop/dune, src/bindings/interop/interop.ml, src/bindings/interop/interop.mli, src/bindings/node/dune, src/bindings/node/node.ml, src/bindings/node/node.mli, src/bindings/vscode/dune, src/bindings/vscode/vscode.ml, src/bindings/vscode/vscode.mli, src/bindings/vscode_languageclient/dune, src/bindings/vscode_languageclient/vscode_languageclient.ml, src/bindings/vscode_languageclient/vscode_languageclient.mli, src/esy.ml, src/import.ml, src/opam.ml, src/path.ml, src/path.mli, src/switchImplIntf.ml, src/vscode_ocaml_platform.ml
It should be available via the Import module
=> Do not open Core_kernel everywhere

CHANGELOG.md, src/cmd.ml
Leftover BuckleScript string interpolation.
=> Fix incomplete error message for missing commands

CHANGELOG.md, syntaxes/ocaml.json
=> Fix quoted string literal highlighting

.github/workflows/workflow.yml, .gitignore, .vscode/launch.json, .vscodeignore, dist/dune, dune, esy.json, package.json, src/dune
This is easier to remember than _build/default
=> Move extension to dist directory

CHANGELOG.md, syntaxes/ocaml.json
See https://github.com/ocamllabs/vscode-ocaml-platform/pull/416
=> Remove styling tag from language

src/bindings/node/node.ml, src/cmd.ml, src/dune_formatter.ml, src/dune_task_provider.ml, src/esy.ml, src/import.ml, src/opam.ml, src/switch_impl_intf.ml, src/terminal_sandbox.ml, src/toolchain.ml, src/vscode_ocaml_platform.ml, vscode/vscode/vscode.ml, vscode/vscode_languageclient/vscode_languageclient.ml
=> Use monadic let operators

CHANGELOG.md, syntaxes/dune-project.json
https://dune.readthedocs.io/en/stable/tests.html#cram-tests
https://discuss.ocaml.org/t/cram-tests-on-short-notice/6256
=> Add syntax highlight support for cram stanza

.github/workflows/workflow.yml, package.json, yarn.lock
=> Add workflow step to publish the extension to Open VSX

src/switch_impl_intf.ml
* Wait for edit to finish
* If edit could not be inserted, show an error message
=> Insert intf tweaks

src/opam.ml
Fixes #512 
The issue occurs when a package listed in the `roots` field of the switch's `switch-state` is not in the `packages` directory. This should never happen and I haven't been able to reproduce it, but if it happens, we simply ignore the dependency.
=> Fix uninstalled Opam packages

CHANGELOG.md, syntaxes/ocaml.json
=> Highlight OCaml source code inside Cinaps comments

vscode/vscode/vscode.ml, vscode/vscode/vscode.mli
Adds changes from the latest VSCode API to bindings.
=> Update VSCode bindings for 1.54 

vscode/vscode/vscode.ml, vscode/vscode/vscode.mli
Adds changes from latest VSCode update.
Should be merged after dependabot updates the VSCode npm dependency for us.
=> Update VSCode bindings for 1.56

Makefile, package.json, src/extension_commands.ml, src/import.ml
This PR is a pair for https://github.com/ocaml/ocaml-lsp/pull/472. 
Commit messages should describe the contents of this PR, and it's best to review by going through commits one-by-one.
=> Better `Construct` support

CHANGES.md, package.json
Fixing clashes with important keybindings in French keyboard
Note: is based on #746 because that PR fixes some extension installation problems; see the single commit relevant to this PR to review
I would completely remove the keybindings but that'd be annoying workflow breaker IMHO
@tmattio , could you please confirm the new keybindings work well with French layout?
=> Update keybindings for holes

Makefile, package-lock.json, package.json
Should fix #729 
Could someone with more JS experience review the PR? 
@tatchi @mnxn ?
=> Fix "open ast explorer" command "argument undefined or null" 

CHANGES.md, src/opam.ml
=> fix detection of opam root when no switch is selected

dune
there's no need to scan astexplorer
=> chore: speed up the dune build

Makefile
makes the makefile unusable from nix
=> chore: remove opam exec from make

.ocamlformat, nix/default.nix, nix/opam-selection.nix
ppxlib is a dependency of our extension and not the bindings.
=> Dependency fixes

CHANGELOG.md, src/opam.ml
check --version of opam before using --global
cc @Khady
=> fix: restore compat with opam 2.0.x

CHANGELOG.md, src/ast_editor.ml
=> Fix automatic closing of files without an extension

CHANGELOG.md, README.md, package.json, src/repl.ml
I have modified package settings and repl script to let the user decides if he wants to use utop or not.
=> Add a setting to Enable/Disable Utop usage

.github/workflows/main.yml
- upgrade to dune 3.0
- upgrade to ocaml 4.14
- upgrade to node 16
=> upgrade node

CHANGELOG.md, languages/ocaml.json
I have modified the ocaml.json file to resolve #182 issue
=> Add indentation rules for comments

.gitignore, .ocamlformat-ignore, .prettierignore, CHANGELOG.md, Makefile, package.json, src-browser/dune, src-browser/vscode_ocaml_platform_web.mli
This reverts commit 536b5290de66166c24316421c60c5eba018ebc03 until there's a fix PR
=> (for now) Revert "Minimal support for web (#962)"

CHANGELOG.md, package.json
ps-id: 8103387d-f7c9-44a2-aa31-9acd29cd8e3a
=> chore: prepare 1.10.8

.git-blame-ignore-revs, .ocamlformat, src-bindings/vscode/vscode.ml, src/ast_editor.ml, src/cm_editor.ml, src/cmd.ml, src/documentation_server.ml, src/dune_task_provider.ml, src/esy.ml, src/extension_commands.ml, src/extension_consts.ml, src/extension_instance.ml, src/import.ml, src/ocaml_lsp.ml, src/ocaml_windows.ml, src/odig.ml, src/opam.ml, src/ppx_tools/dumpast.ml, src/ppx_tools/traverse_ast.ml, src/ppx_tools/traverse_ast2.ml, src/repl.ml, src/sandbox.ml, src/settings.ml, src/switch_impl_intf.ml, src/treeview_commands.ml, src/treeview_help.ml, src/treeview_sandbox.ml, src/treeview_switches.ml, src/vscode_ocaml_platform.ml
similar to https://github.com/ocaml/ocaml-lsp/pull/856
=> formatting: do not wrap function args

CHANGELOG.md, package.json
ps-id: f73c9408-dc6d-430d-a027-67f8da002f40
=> chore: prepare 1.11.0

CHANGELOG.md, package.json, src/extension_instance.ml, src/settings.ml, src/settings.mli
=> add setting to pass extra args to ocamllsp

.github/workflows/main.yml
Confirmed here:
https://github.com/ocamllabs/vscode-ocaml-platform/pull/1106#discussion_r1212989960
=> Disable Windows CI job

Makefile, flake.nix
It creates shell that is able to debug extension with provided vs code
=> chore: Fix `nix develop`

.github/workflows/changelog.yml
The action has been updated so it accepts a filename to be checked.
Pointed out by @smorimoto.
=> Update Action to check the right file

CHANGELOG.md
=> chore: fix change log

CHANGELOG.md, syntaxes/dune-project.json
https://dune.readthedocs.io/en/stable/dune-files.html#stanza-source
=> Add more patterns to `opam-metadata.source`

package.json
=> chore: prepare 1.13.0

.vscode/tasks.json
=> chore: fix build task

CHANGELOG.md, syntaxes/dune.json
Fixes #1089 
| - | - |
| ![before](https://github.com/ocamllabs/vscode-ocaml-platform/assets/25037249/44fa3c86-0be7-436f-a36a-f21cc42a89b8) | ![after](https://github.com/ocamllabs/vscode-ocaml-platform/assets/25037249/3e25b474-2370-4c27-a23b-f83830f07625) |
=> Fix highlighting of flags stanza in dune files

README.md
See https://github.com/hackwaly/ocamlearlybird/issues/20#issuecomment-1658203855
=> Add instructions for debugging with dune 3.0+

CHANGELOG.md
=> chore: fix CHANGES

Makefile
=> chore: remove --root .

CHANGELOG.md, package.json
=> chore: prepare 1.13.1

CHANGELOG.md, package.json
https://github.com/ocamllabs/vscode-ocaml-platform/compare/1.13.1...master
=> Prepare 1.13.2

.prettierignore, CHANGELOG.md, package.json, yarn.lock
- https://github.com/ocamllabs/vscode-ocaml-platform/pull/1274
=> Prepare 1.14.0

package.json
| :-: | :-: |
| <img width="1080" alt="Screenshot 2023-11-30 at 18 59 59" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/38746192/754454c8-4325-4db1-a3a1-030684b61e53"> | <img width="1080" alt="Screenshot 2023-11-30 at 19 00 27" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/38746192/32d784b2-1830-4cb6-bd94-2d5955f41744"> |
Ref: https://code.visualstudio.com/api/references/extension-manifest
=> Change the gallery banner to OCaml color

CHANGELOG.md, package.json
=> Prepare 1.14.2

src/extension_instance.ml, src/extension_instance.mli, src/vscode_ocaml_platform.ml
=> refactor: remove unnecessary optional arguments

CHANGELOG.md
=> chore: fix formatting of CHANGES

CHANGELOG.md
=> chore: add missing PR number to CHANGES

flake.lock, flake.nix
=> chore: update nix config

CHANGELOG.md, syntaxes/dune.json
=> Fix broken syntax highlighting for a wildcard in the env stanza

CHANGELOG.md, package.json, yarn.lock
- #1320
- #1321
- #1322 
- #1334
=> Prepare 1.15.0

CHANGELOG.md, snippets/dune.json
https://dune.readthedocs.io/en/stable/dune-files.html#alias
This work is paid for by Ahrefs
=> add snippet for dune alias stanza

CHANGELOG.md, package.json, yarn.lock
- https://github.com/ocamllabs/vscode-ocaml-platform/pull/1369
=> Prepare 1.16.2

CHANGELOG.md, package.json, yarn.lock
This change is required for the #1307
=> VSCode 1.86.0

.github/workflows/main.yml, CHANGELOG.md, package.json, yarn.lock
=> Prepare 1.17.1

README.md
=> Fix broken link to dune docs in README

.github/workflows/main.yml
Fixes https://github.com/ocamllabs/vscode-ocaml-platform/actions/runs/10544155490/job/29212898363#step:16:22
=> Set `permissions.contents` to `write`

flake.nix
=> chore(nix): use newest yarn

.github/workflows/main.yml, .github/workflows/opam-dependency-submission.yml, dune-project, vscode-ocaml-platform.opam
hope i'm not missing anything
this allows us to have same switch for olsp & this project
=> update to ocaml 5

CHANGELOG.md, src/extension_instance.ml
Fixes https://github.com/ocamllabs/vscode-ocaml-platform/issues/1647
I manually tested this on windows and ubuntu.
=> Fix cwd formatting on windows

dune-project, vscode-ocaml-platform.opam, vscode.opam
Blocker:
- https://github.com/NixOS/nixpkgs/pull/361854
=> Update dune to 3.17
